	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_hyoushigi.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_kick.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/sc88pro_tr909_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/unused_sc55_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/sc88pro_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/sc88pro_mute_high_conga.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/sc88pro_open_low_conga.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/sd90_cowbell.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/unused_heart_of_asia_indian_drum.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/sd90_open_triangle.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/sc88pro_jingle_bell.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/ethnic_flavours_atarigane.bin"

	.align 2
DirectSoundWaveData_sc88pro_taiko::
	.incbin "sound/direct_sound_samples/sc88pro_taiko.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_kotsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39:: @N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up
	.incbin "sound/direct_sound_samples/sc88pro_tuba_39.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_low.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_high.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_unknown_1::
	.incbin "sound/direct_sound_samples/unknown_01.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_unknown_2::
	.incbin "sound/direct_sound_samples/unknown_02.bin"

	.align 2
DirectSoundWaveData_unknown_3::
	.incbin "sound/direct_sound_samples/unknown_03.bin"

	.align 2
DirectSoundWaveData_unknown_4::
	.incbin "sound/direct_sound_samples/unknown_04.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.align 2
DirectSoundWaveData_unknown_5::
	.incbin "sound/direct_sound_samples/unknown_05.bin"

	.align 2
DirectSoundWaveData_unknown_6::
	.incbin "sound/direct_sound_samples/unknown_06.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.align 2
DirectSoundWaveData_unknown_7::
	.incbin "sound/direct_sound_samples/unknown_07.bin"

	.align 2
DirectSoundWaveData_unknown_8::
	.incbin "sound/direct_sound_samples/unknown_08.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.align 2
DirectSoundWaveData_unknown_9::
	.incbin "sound/direct_sound_samples/unknown_09.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.align 2
DirectSoundWaveData_unknown_10::
	.incbin "sound/direct_sound_samples/unknown_10.bin"

	.align 2
DirectSoundWaveData_unknown_11::
	.incbin "sound/direct_sound_samples/unknown_11.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.align 2
DirectSoundWaveData_unknown_12::
	.incbin "sound/direct_sound_samples/unknown_12.bin"

	.align 2
DirectSoundWaveData_unknown_13::
	.incbin "sound/direct_sound_samples/unknown_13.bin"

	.align 2
DirectSoundWaveData_unknown_14::
	.incbin "sound/direct_sound_samples/unknown_14.bin"

	.align 2
DirectSoundWaveData_unknown_15::
	.incbin "sound/direct_sound_samples/unknown_15.bin"

	.align 2
DirectSoundWaveData_unknown_16::
	.incbin "sound/direct_sound_samples/unknown_16.bin"

	.align 2
DirectSoundWaveData_unknown_17::
	.incbin "sound/direct_sound_samples/unknown_17.bin"

	.align 2
Cry_Bulbasaur::
	.incbin "sound/direct_sound_samples/cries/bulbasaur.bin"

	.align 2
Cry_Ivysaur::
	.incbin "sound/direct_sound_samples/cries/ivysaur.bin"

	.align 2
Cry_Venusaur::
	.incbin "sound/direct_sound_samples/cries/venusaur.bin"

	.align 2
Cry_Charmander::
	.incbin "sound/direct_sound_samples/cries/charmander.bin"

	.align 2
Cry_Charmeleon::
	.incbin "sound/direct_sound_samples/cries/charmeleon.bin"

	.align 2
Cry_Charizard::
	.incbin "sound/direct_sound_samples/cries/charizard.bin"

	.align 2
Cry_Squirtle::
	.incbin "sound/direct_sound_samples/cries/squirtle.bin"

	.align 2
Cry_Wartortle::
	.incbin "sound/direct_sound_samples/cries/wartortle.bin"

	.align 2
Cry_Blastoise::
	.incbin "sound/direct_sound_samples/cries/blastoise.bin"

	.align 2
Cry_Caterpie::
	.incbin "sound/direct_sound_samples/cries/caterpie.bin"

	.align 2
Cry_Metapod::
	.incbin "sound/direct_sound_samples/cries/metapod.bin"

	.align 2
Cry_Butterfree::
	.incbin "sound/direct_sound_samples/cries/butterfree.bin"

	.align 2
Cry_Weedle::
	.incbin "sound/direct_sound_samples/cries/weedle.bin"

	.align 2
Cry_Kakuna::
	.incbin "sound/direct_sound_samples/cries/kakuna.bin"

	.align 2
Cry_Beedrill::
	.incbin "sound/direct_sound_samples/cries/beedrill.bin"

	.align 2
Cry_Pidgey::
	.incbin "sound/direct_sound_samples/cries/pidgey.bin"

	.align 2
Cry_Pidgeotto::
	.incbin "sound/direct_sound_samples/cries/pidgeotto.bin"

	.align 2
Cry_Pidgeot::
	.incbin "sound/direct_sound_samples/cries/pidgeot.bin"

	.align 2
Cry_Rattata::
	.incbin "sound/direct_sound_samples/cries/rattata.bin"

	.align 2
Cry_Raticate::
	.incbin "sound/direct_sound_samples/cries/raticate.bin"

	.align 2
Cry_Spearow::
	.incbin "sound/direct_sound_samples/cries/spearow.bin"

	.align 2
Cry_Fearow::
	.incbin "sound/direct_sound_samples/cries/fearow.bin"

	.align 2
Cry_Ekans::
	.incbin "sound/direct_sound_samples/cries/ekans.bin"

	.align 2
Cry_Arbok::
	.incbin "sound/direct_sound_samples/cries/arbok.bin"

	.align 2
Cry_Pikachu::
	.incbin "sound/direct_sound_samples/cries/pikachu.bin"

	.align 2
Cry_Raichu::
	.incbin "sound/direct_sound_samples/cries/raichu.bin"

	.align 2
Cry_Sandshrew::
	.incbin "sound/direct_sound_samples/cries/sandshrew.bin"

	.align 2
Cry_Sandslash::
	.incbin "sound/direct_sound_samples/cries/sandslash.bin"

	.align 2
Cry_NidoranF::
	.incbin "sound/direct_sound_samples/cries/nidoran_f.bin"

	.align 2
Cry_Nidorina::
	.incbin "sound/direct_sound_samples/cries/nidorina.bin"

	.align 2
Cry_Nidoqueen::
	.incbin "sound/direct_sound_samples/cries/nidoqueen.bin"

	.align 2
Cry_NidoranM::
	.incbin "sound/direct_sound_samples/cries/nidoran_m.bin"

	.align 2
Cry_Nidorino::
	.incbin "sound/direct_sound_samples/cries/nidorino.bin"

	.align 2
Cry_Nidoking::
	.incbin "sound/direct_sound_samples/cries/nidoking.bin"

	.align 2
Cry_Clefairy::
	.incbin "sound/direct_sound_samples/cries/clefairy.bin"

	.align 2
Cry_Clefable::
	.incbin "sound/direct_sound_samples/cries/clefable.bin"

	.align 2
Cry_Vulpix::
	.incbin "sound/direct_sound_samples/cries/vulpix.bin"

	.align 2
Cry_Ninetales::
	.incbin "sound/direct_sound_samples/cries/ninetales.bin"

	.align 2
Cry_Jigglypuff::
	.incbin "sound/direct_sound_samples/cries/jigglypuff.bin"

	.align 2
Cry_Wigglytuff::
	.incbin "sound/direct_sound_samples/cries/wigglytuff.bin"

	.align 2
Cry_Zubat::
	.incbin "sound/direct_sound_samples/cries/zubat.bin"

	.align 2
Cry_Golbat::
	.incbin "sound/direct_sound_samples/cries/golbat.bin"

	.align 2
Cry_Oddish::
	.incbin "sound/direct_sound_samples/cries/oddish.bin"

	.align 2
Cry_Gloom::
	.incbin "sound/direct_sound_samples/cries/gloom.bin"

	.align 2
Cry_Vileplume::
	.incbin "sound/direct_sound_samples/cries/vileplume.bin"

	.align 2
Cry_Paras::
	.incbin "sound/direct_sound_samples/cries/paras.bin"

	.align 2
Cry_Parasect::
	.incbin "sound/direct_sound_samples/cries/parasect.bin"

	.align 2
Cry_Venonat::
	.incbin "sound/direct_sound_samples/cries/venonat.bin"

	.align 2
Cry_Venomoth::
	.incbin "sound/direct_sound_samples/cries/venomoth.bin"

	.align 2
Cry_Diglett::
	.incbin "sound/direct_sound_samples/cries/diglett.bin"

	.align 2
Cry_Dugtrio::
	.incbin "sound/direct_sound_samples/cries/dugtrio.bin"

	.align 2
Cry_Meowth::
	.incbin "sound/direct_sound_samples/cries/meowth.bin"

	.align 2
Cry_Persian::
	.incbin "sound/direct_sound_samples/cries/persian.bin"

	.align 2
Cry_Psyduck::
	.incbin "sound/direct_sound_samples/cries/psyduck.bin"

	.align 2
Cry_Golduck::
	.incbin "sound/direct_sound_samples/cries/golduck.bin"

	.align 2
Cry_Mankey::
	.incbin "sound/direct_sound_samples/cries/mankey.bin"

	.align 2
Cry_Primeape::
	.incbin "sound/direct_sound_samples/cries/primeape.bin"

	.align 2
Cry_Growlithe::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Arcanine::
	.incbin "sound/direct_sound_samples/cries/arcanine.bin"

	.align 2
Cry_Poliwag::
	.incbin "sound/direct_sound_samples/cries/poliwag.bin"

	.align 2
Cry_Poliwhirl::
	.incbin "sound/direct_sound_samples/cries/poliwhirl.bin"

	.align 2
Cry_Poliwrath::
	.incbin "sound/direct_sound_samples/cries/poliwrath.bin"

	.align 2
Cry_Abra::
	.incbin "sound/direct_sound_samples/cries/abra.bin"

	.align 2
Cry_Kadabra::
	.incbin "sound/direct_sound_samples/cries/kadabra.bin"

	.align 2
Cry_Alakazam::
	.incbin "sound/direct_sound_samples/cries/alakazam.bin"

	.align 2
Cry_Machop::
	.incbin "sound/direct_sound_samples/cries/machop.bin"

	.align 2
Cry_Machoke::
	.incbin "sound/direct_sound_samples/cries/machoke.bin"

	.align 2
Cry_Machamp::
	.incbin "sound/direct_sound_samples/cries/machamp.bin"

	.align 2
Cry_Bellsprout::
	.incbin "sound/direct_sound_samples/cries/bellsprout.bin"

	.align 2
Cry_Weepinbell::
	.incbin "sound/direct_sound_samples/cries/weepinbell.bin"

	.align 2
Cry_Victreebel::
	.incbin "sound/direct_sound_samples/cries/victreebel.bin"

	.align 2
Cry_Tentacool::
	.incbin "sound/direct_sound_samples/cries/tentacool.bin"

	.align 2
Cry_Tentacruel::
	.incbin "sound/direct_sound_samples/cries/tentacruel.bin"

	.align 2
Cry_Geodude::
	.incbin "sound/direct_sound_samples/cries/geodude.bin"

	.align 2
Cry_Graveler::
	.incbin "sound/direct_sound_samples/cries/graveler.bin"

	.align 2
Cry_Golem::
	.incbin "sound/direct_sound_samples/cries/golem.bin"

	.align 2
Cry_Ponyta::
	.incbin "sound/direct_sound_samples/cries/ponyta.bin"

	.align 2
Cry_Rapidash::
	.incbin "sound/direct_sound_samples/cries/rapidash.bin"

	.align 2
Cry_Slowpoke::
	.incbin "sound/direct_sound_samples/cries/slowpoke.bin"

	.align 2
Cry_Slowbro::
	.incbin "sound/direct_sound_samples/cries/slowbro.bin"

	.align 2
Cry_Magnemite::
	.incbin "sound/direct_sound_samples/cries/magnemite.bin"

	.align 2
Cry_Magneton::
	.incbin "sound/direct_sound_samples/cries/magneton.bin"

	.align 2
Cry_Farfetchd::
	.incbin "sound/direct_sound_samples/cries/farfetchd.bin"

	.align 2
Cry_Doduo::
	.incbin "sound/direct_sound_samples/cries/doduo.bin"

	.align 2
Cry_Dodrio::
	.incbin "sound/direct_sound_samples/cries/dodrio.bin"

	.align 2
Cry_Seel::
	.incbin "sound/direct_sound_samples/cries/seel.bin"

	.align 2
Cry_Dewgong::
	.incbin "sound/direct_sound_samples/cries/dewgong.bin"

	.align 2
Cry_Grimer::
	.incbin "sound/direct_sound_samples/cries/grimer.bin"

	.align 2
Cry_Muk::
	.incbin "sound/direct_sound_samples/cries/muk.bin"

	.align 2
Cry_Shellder::
	.incbin "sound/direct_sound_samples/cries/shellder.bin"

	.align 2
Cry_Cloyster::
	.incbin "sound/direct_sound_samples/cries/cloyster.bin"

	.align 2
Cry_Gastly::
	.incbin "sound/direct_sound_samples/cries/gastly.bin"

	.align 2
Cry_Haunter::
	.incbin "sound/direct_sound_samples/cries/haunter.bin"

	.align 2
Cry_Gengar::
	.incbin "sound/direct_sound_samples/cries/gengar.bin"

	.align 2
Cry_Onix::
	.incbin "sound/direct_sound_samples/cries/onix.bin"

	.align 2
Cry_Drowzee::
	.incbin "sound/direct_sound_samples/cries/drowzee.bin"

	.align 2
Cry_Hypno::
	.incbin "sound/direct_sound_samples/cries/hypno.bin"

	.align 2
Cry_Krabby::
	.incbin "sound/direct_sound_samples/cries/krabby.bin"

	.align 2
Cry_Kingler::
	.incbin "sound/direct_sound_samples/cries/kingler.bin"

	.align 2
Cry_Voltorb::
	.incbin "sound/direct_sound_samples/cries/voltorb.bin"

	.align 2
Cry_Electrode::
	.incbin "sound/direct_sound_samples/cries/electrode.bin"

	.align 2
Cry_Exeggcute::
	.incbin "sound/direct_sound_samples/cries/exeggcute.bin"

	.align 2
Cry_Exeggutor::
	.incbin "sound/direct_sound_samples/cries/exeggutor.bin"

	.align 2
Cry_Cubone::
	.incbin "sound/direct_sound_samples/cries/cubone.bin"

	.align 2
Cry_Marowak::
	.incbin "sound/direct_sound_samples/cries/marowak.bin"

	.align 2
Cry_Hitmonlee::
	.incbin "sound/direct_sound_samples/cries/hitmonlee.bin"

	.align 2
Cry_Hitmonchan::
	.incbin "sound/direct_sound_samples/cries/hitmonchan.bin"

	.align 2
Cry_Lickitung::
	.incbin "sound/direct_sound_samples/cries/lickitung.bin"

	.align 2
Cry_Koffing::
	.incbin "sound/direct_sound_samples/cries/koffing.bin"

	.align 2
Cry_Weezing::
	.incbin "sound/direct_sound_samples/cries/weezing.bin"

	.align 2
Cry_Rhyhorn::
	.incbin "sound/direct_sound_samples/cries/rhyhorn.bin"

	.align 2
Cry_Rhydon::
	.incbin "sound/direct_sound_samples/cries/rhydon.bin"

	.align 2
Cry_Chansey::
	.incbin "sound/direct_sound_samples/cries/chansey.bin"

	.align 2
Cry_Tangela::
	.incbin "sound/direct_sound_samples/cries/tangela.bin"

	.align 2
Cry_Kangaskhan::
	.incbin "sound/direct_sound_samples/cries/kangaskhan.bin"

	.align 2
Cry_Horsea::
	.incbin "sound/direct_sound_samples/cries/horsea.bin"

	.align 2
Cry_Seadra::
	.incbin "sound/direct_sound_samples/cries/seadra.bin"

	.align 2
Cry_Goldeen::
	.incbin "sound/direct_sound_samples/cries/goldeen.bin"

	.align 2
Cry_Seaking::
	.incbin "sound/direct_sound_samples/cries/seaking.bin"

	.align 2
Cry_Staryu::
	.incbin "sound/direct_sound_samples/cries/staryu.bin"

	.align 2
Cry_Starmie::
	.incbin "sound/direct_sound_samples/cries/starmie.bin"

	.align 2
Cry_MrMime::
	.incbin "sound/direct_sound_samples/cries/mr_mime.bin"

	.align 2
Cry_Scyther::
	.incbin "sound/direct_sound_samples/cries/scyther.bin"

	.align 2
Cry_Jynx::
	.incbin "sound/direct_sound_samples/cries/jynx.bin"

	.align 2
Cry_Electabuzz::
	.incbin "sound/direct_sound_samples/cries/electabuzz.bin"

	.align 2
Cry_Magmar::
	.incbin "sound/direct_sound_samples/cries/magmar.bin"

	.align 2
Cry_Pinsir::
	.incbin "sound/direct_sound_samples/cries/pinsir.bin"

	.align 2
Cry_Tauros::
	.incbin "sound/direct_sound_samples/cries/tauros.bin"

	.align 2
Cry_Magikarp::
	.incbin "sound/direct_sound_samples/cries/magikarp.bin"

	.align 2
Cry_Gyarados::
	.incbin "sound/direct_sound_samples/cries/gyarados.bin"

	.align 2
Cry_Lapras::
	.incbin "sound/direct_sound_samples/cries/lapras.bin"

	.align 2
Cry_Ditto::
	.incbin "sound/direct_sound_samples/cries/ditto.bin"

	.align 2
Cry_Eevee::
	.incbin "sound/direct_sound_samples/cries/eevee.bin"

	.align 2
Cry_Vaporeon::
	.incbin "sound/direct_sound_samples/cries/vaporeon.bin"

	.align 2
Cry_Jolteon::
	.incbin "sound/direct_sound_samples/cries/jolteon.bin"

	.align 2
Cry_Flareon::
	.incbin "sound/direct_sound_samples/cries/flareon.bin"

	.align 2
Cry_Porygon::
	.incbin "sound/direct_sound_samples/cries/porygon.bin"

	.align 2
Cry_Omanyte::
	.incbin "sound/direct_sound_samples/cries/omanyte.bin"

	.align 2
Cry_Omastar::
	.incbin "sound/direct_sound_samples/cries/omastar.bin"

	.align 2
Cry_Kabuto::
	.incbin "sound/direct_sound_samples/cries/kabuto.bin"

	.align 2
Cry_Kabutops::
	.incbin "sound/direct_sound_samples/cries/kabutops.bin"

	.align 2
Cry_Aerodactyl::
	.incbin "sound/direct_sound_samples/cries/aerodactyl.bin"

	.align 2
Cry_Snorlax::
	.incbin "sound/direct_sound_samples/cries/snorlax.bin"

	.align 2
Cry_Articuno::
	.incbin "sound/direct_sound_samples/cries/articuno.bin"

	.align 2
Cry_Zapdos::
	.incbin "sound/direct_sound_samples/cries/zapdos.bin"

	.align 2
Cry_Moltres::
	.incbin "sound/direct_sound_samples/cries/moltres.bin"

	.align 2
Cry_Dratini::
	.incbin "sound/direct_sound_samples/cries/dratini.bin"

	.align 2
Cry_Dragonair::
	.incbin "sound/direct_sound_samples/cries/dragonair.bin"

	.align 2
Cry_Dragonite::
	.incbin "sound/direct_sound_samples/cries/dragonite.bin"

	.align 2
Cry_Mewtwo::
	.incbin "sound/direct_sound_samples/cries/mewtwo.bin"

	.align 2
Cry_Mew::
	.incbin "sound/direct_sound_samples/cries/mew.bin"

	.align 2
Cry_Chikorita::
	.incbin "sound/direct_sound_samples/cries/chikorita.bin"

	.align 2
Cry_Bayleef::
	.incbin "sound/direct_sound_samples/cries/bayleef.bin"

	.align 2
Cry_Meganium::
	.incbin "sound/direct_sound_samples/cries/meganium.bin"

	.align 2
Cry_Cyndaquil::
	.incbin "sound/direct_sound_samples/cries/cyndaquil.bin"

	.align 2
Cry_Quilava::
	.incbin "sound/direct_sound_samples/cries/quilava.bin"

	.align 2
Cry_Typhlosion::
	.incbin "sound/direct_sound_samples/cries/typhlosion.bin"

	.align 2
Cry_Totodile::
	.incbin "sound/direct_sound_samples/cries/totodile.bin"

	.align 2
Cry_Croconaw::
	.incbin "sound/direct_sound_samples/cries/croconaw.bin"

	.align 2
Cry_Feraligatr::
	.incbin "sound/direct_sound_samples/cries/feraligatr.bin"

	.align 2
Cry_Sentret::
	.incbin "sound/direct_sound_samples/cries/sentret.bin"

	.align 2
Cry_Furret::
	.incbin "sound/direct_sound_samples/cries/furret.bin"

	.align 2
Cry_Hoothoot::
	.incbin "sound/direct_sound_samples/cries/hoothoot.bin"

	.align 2
Cry_Noctowl::
	.incbin "sound/direct_sound_samples/cries/noctowl.bin"

	.align 2
Cry_Ledyba::
	.incbin "sound/direct_sound_samples/cries/ledyba.bin"

	.align 2
Cry_Ledian::
	.incbin "sound/direct_sound_samples/cries/ledian.bin"

	.align 2
Cry_Spinarak::
	.incbin "sound/direct_sound_samples/cries/spinarak.bin"

	.align 2
Cry_Ariados::
	.incbin "sound/direct_sound_samples/cries/ariados.bin"

	.align 2
Cry_Crobat::
	.incbin "sound/direct_sound_samples/cries/crobat.bin"

	.align 2
Cry_Chinchou::
	.incbin "sound/direct_sound_samples/cries/chinchou.bin"

	.align 2
Cry_Lanturn::
	.incbin "sound/direct_sound_samples/cries/lanturn.bin"

	.align 2
Cry_Pichu::
	.incbin "sound/direct_sound_samples/cries/pichu.bin"

	.align 2
Cry_Cleffa::
	.incbin "sound/direct_sound_samples/cries/cleffa.bin"

	.align 2
Cry_Igglybuff::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Togepi::
	.incbin "sound/direct_sound_samples/cries/togepi.bin"

	.align 2
Cry_Togetic::
	.incbin "sound/direct_sound_samples/cries/togetic.bin"

	.align 2
Cry_Natu::
	.incbin "sound/direct_sound_samples/cries/natu.bin"

	.align 2
Cry_Xatu::
	.incbin "sound/direct_sound_samples/cries/xatu.bin"

	.align 2
Cry_Mareep::
	.incbin "sound/direct_sound_samples/cries/mareep.bin"

	.align 2
Cry_Flaaffy::
	.incbin "sound/direct_sound_samples/cries/flaaffy.bin"

	.align 2
Cry_Ampharos::
	.incbin "sound/direct_sound_samples/cries/ampharos.bin"

	.align 2
Cry_Bellossom::
	.incbin "sound/direct_sound_samples/cries/bellossom.bin"

	.align 2
Cry_Marill::
	.incbin "sound/direct_sound_samples/cries/marill.bin"

	.align 2
Cry_Azumarill::
	.incbin "sound/direct_sound_samples/cries/azumarill.bin"

	.align 2
Cry_Sudowoodo::
	.incbin "sound/direct_sound_samples/cries/sudowoodo.bin"

	.align 2
Cry_Politoed::
	.incbin "sound/direct_sound_samples/cries/politoed.bin"

	.align 2
Cry_Hoppip::
	.incbin "sound/direct_sound_samples/cries/hoppip.bin"

	.align 2
Cry_Skiploom::
	.incbin "sound/direct_sound_samples/cries/skiploom.bin"

	.align 2
Cry_Jumpluff::
	.incbin "sound/direct_sound_samples/cries/jumpluff.bin"

	.align 2
Cry_Aipom::
	.incbin "sound/direct_sound_samples/cries/aipom.bin"

	.align 2
Cry_Sunkern::
	.incbin "sound/direct_sound_samples/cries/sunkern.bin"

	.align 2
Cry_Sunflora::
	.incbin "sound/direct_sound_samples/cries/sunflora.bin"

	.align 2
Cry_Yanma::
	.incbin "sound/direct_sound_samples/cries/yanma.bin"

	.align 2
Cry_Wooper::
	.incbin "sound/direct_sound_samples/cries/wooper.bin"

	.align 2
Cry_Quagsire::
	.incbin "sound/direct_sound_samples/cries/quagsire.bin"

	.align 2
Cry_Espeon::
	.incbin "sound/direct_sound_samples/cries/espeon.bin"

	.align 2
Cry_Umbreon::
	.incbin "sound/direct_sound_samples/cries/umbreon.bin"

	.align 2
Cry_Murkrow::
	.incbin "sound/direct_sound_samples/cries/murkrow.bin"

	.align 2
Cry_Slowking::
	.incbin "sound/direct_sound_samples/cries/slowking.bin"

	.align 2
Cry_Misdreavus::
	.incbin "sound/direct_sound_samples/cries/misdreavus.bin"

	.align 2
Cry_Unown::
	.incbin "sound/direct_sound_samples/cries/unown.bin"

	.align 2
Cry_Wobbuffet::
	.incbin "sound/direct_sound_samples/cries/wobbuffet.bin"

	.align 2
Cry_Girafarig::
	.incbin "sound/direct_sound_samples/cries/girafarig.bin"

	.align 2
Cry_Pineco::
	.incbin "sound/direct_sound_samples/cries/pineco.bin"

	.align 2
Cry_Forretress::
	.incbin "sound/direct_sound_samples/cries/forretress.bin"

	.align 2
Cry_Dunsparce::
	.incbin "sound/direct_sound_samples/cries/dunsparce.bin"

	.align 2
Cry_Gligar::
	.incbin "sound/direct_sound_samples/cries/gligar.bin"

	.align 2
Cry_Steelix::
	.incbin "sound/direct_sound_samples/cries/steelix.bin"

	.align 2
Cry_Snubbull::
	.incbin "sound/direct_sound_samples/cries/snubbull.bin"

	.align 2
Cry_Granbull::
	.incbin "sound/direct_sound_samples/cries/granbull.bin"

	.align 2
Cry_Qwilfish::
	.incbin "sound/direct_sound_samples/cries/qwilfish.bin"

	.align 2
Cry_Scizor::
	.incbin "sound/direct_sound_samples/cries/scizor.bin"

	.align 2
Cry_Shuckle::
	.incbin "sound/direct_sound_samples/cries/shuckle.bin"

	.align 2
Cry_Heracross::
	.incbin "sound/direct_sound_samples/cries/heracross.bin"

	.align 2
Cry_Sneasel::
	.incbin "sound/direct_sound_samples/cries/sneasel.bin"

	.align 2
Cry_Teddiursa::
	.incbin "sound/direct_sound_samples/cries/teddiursa.bin"

	.align 2
Cry_Ursaring::
	.incbin "sound/direct_sound_samples/cries/ursaring.bin"

	.align 2
Cry_Slugma::
	.incbin "sound/direct_sound_samples/cries/slugma.bin"

	.align 2
Cry_Magcargo::
	.incbin "sound/direct_sound_samples/cries/magcargo.bin"

	.align 2
Cry_Swinub::
	.incbin "sound/direct_sound_samples/cries/swinub.bin"

	.align 2
Cry_Piloswine::
	.incbin "sound/direct_sound_samples/cries/piloswine.bin"

	.align 2
Cry_Corsola::
	.incbin "sound/direct_sound_samples/cries/corsola.bin"

	.align 2
Cry_Remoraid::
	.incbin "sound/direct_sound_samples/cries/remoraid.bin"

	.align 2
Cry_Octillery::
	.incbin "sound/direct_sound_samples/cries/octillery.bin"

	.align 2
Cry_Delibird::
	.incbin "sound/direct_sound_samples/cries/delibird.bin"

	.align 2
Cry_Mantine::
	.incbin "sound/direct_sound_samples/cries/mantine.bin"

	.align 2
Cry_Skarmory::
	.incbin "sound/direct_sound_samples/cries/skarmory.bin"

	.align 2
Cry_Houndour::
	.incbin "sound/direct_sound_samples/cries/houndour.bin"

	.align 2
Cry_Houndoom::
	.incbin "sound/direct_sound_samples/cries/houndoom.bin"

	.align 2
Cry_Kingdra::
	.incbin "sound/direct_sound_samples/cries/kingdra.bin"

	.align 2
Cry_Phanpy::
	.incbin "sound/direct_sound_samples/cries/phanpy.bin"

	.align 2
Cry_Donphan::
	.incbin "sound/direct_sound_samples/cries/donphan.bin"

	.align 2
Cry_Porygon2::
	.incbin "sound/direct_sound_samples/cries/porygon2.bin"

	.align 2
Cry_Stantler::
	.incbin "sound/direct_sound_samples/cries/stantler.bin"

	.align 2
Cry_Smeargle::
	.incbin "sound/direct_sound_samples/cries/smeargle.bin"

	.align 2
Cry_Tyrogue::
	.incbin "sound/direct_sound_samples/cries/tyrogue.bin"

	.align 2
Cry_Hitmontop::
	.incbin "sound/direct_sound_samples/cries/hitmontop.bin"

	.align 2
Cry_Smoochum::
	.incbin "sound/direct_sound_samples/cries/smoochum.bin"

	.align 2
Cry_Elekid::
	.incbin "sound/direct_sound_samples/cries/elekid.bin"

	.align 2
Cry_Magby::
	.incbin "sound/direct_sound_samples/cries/magby.bin"

	.align 2
Cry_Miltank::
	.incbin "sound/direct_sound_samples/cries/miltank.bin"

	.align 2
Cry_Blissey::
	.incbin "sound/direct_sound_samples/cries/blissey.bin"

	.align 2
Cry_Raikou::
	.incbin "sound/direct_sound_samples/cries/raikou.bin"

	.align 2
Cry_Entei::
	.incbin "sound/direct_sound_samples/cries/entei.bin"

	.align 2
Cry_Suicune::
	.incbin "sound/direct_sound_samples/cries/suicune.bin"

	.align 2
Cry_Larvitar::
	.incbin "sound/direct_sound_samples/cries/larvitar.bin"

	.align 2
Cry_Pupitar::
	.incbin "sound/direct_sound_samples/cries/pupitar.bin"

	.align 2
Cry_Tyranitar::
	.incbin "sound/direct_sound_samples/cries/tyranitar.bin"

	.align 2
Cry_Lugia::
	.incbin "sound/direct_sound_samples/cries/lugia.bin"

	.align 2
Cry_HoOh::
	.incbin "sound/direct_sound_samples/cries/ho_oh.bin"

	.align 2
Cry_Celebi::
	.incbin "sound/direct_sound_samples/cries/celebi.bin"

	.align 2
Cry_Kecleon::
	.incbin "sound/direct_sound_samples/cries/kecleon.bin"

	.align 2
Cry_Roselia::
	.incbin "sound/direct_sound_samples/cries/roselia.bin"

	.align 2
Cry_Torkoal::
	.incbin "sound/direct_sound_samples/cries/torkoal.bin"

	.align 2
Cry_Electrike::
	.incbin "sound/direct_sound_samples/cries/electrike.bin"

	.align 2
Cry_Manectric::
	.incbin "sound/direct_sound_samples/cries/manectric.bin"

	.align 2
Cry_Duskull::
	.incbin "sound/direct_sound_samples/cries/duskull.bin"

	.align 2
Cry_Latias::
	.incbin "sound/direct_sound_samples/cries/latias.bin"

	.align 2
Cry_Wynaut::
	.incbin "sound/direct_sound_samples/cries/wynaut.bin"

	.align 2
Cry_Seviper::
	.incbin "sound/direct_sound_samples/cries/seviper.bin"

	.align 2
Cry_Sharpedo::
	.incbin "sound/direct_sound_samples/cries/sharpedo.bin"

	.align 2
Cry_Zangoose::
	.incbin "sound/direct_sound_samples/cries/zangoose.bin"

	.align 2
Cry_Azurill::
	.incbin "sound/direct_sound_samples/cries/azurill.bin"

	.align 2
Cry_Swablu::
	.incbin "sound/direct_sound_samples/cries/swablu.bin"

	.align 2
Cry_Altaria::
	.incbin "sound/direct_sound_samples/cries/altaria.bin"

	.align 2
Cry_Unused265::
	.incbin "sound/direct_sound_samples/cries/unused_265.bin"

	.align 2
Cry_Taillow::
	.incbin "sound/direct_sound_samples/cries/taillow.bin"

	.align 2
Cry_Swellow::
	.incbin "sound/direct_sound_samples/cries/swellow.bin"

	.align 2
Cry_Unused268::
	.incbin "sound/direct_sound_samples/cries/unused_268.bin"

	.align 2
Cry_Spinda::
	.incbin "sound/direct_sound_samples/cries/spinda.bin"

	.align 2
Cry_Torchic::
	.incbin "sound/direct_sound_samples/cries/torchic.bin"

	.align 2
Cry_Combusken::
	.incbin "sound/direct_sound_samples/cries/combusken.bin"

	.align 2
Cry_Blaziken::
	.incbin "sound/direct_sound_samples/cries/blaziken.bin"

	.align 2
Cry_Treecko::
	.incbin "sound/direct_sound_samples/cries/treecko.bin"

	.align 2
Cry_Grovyle::
	.incbin "sound/direct_sound_samples/cries/grovyle.bin"

	.align 2
Cry_Sceptile::
	.incbin "sound/direct_sound_samples/cries/sceptile.bin"

	.align 2
Cry_Mudkip::
	.incbin "sound/direct_sound_samples/cries/mudkip.bin"

	.align 2
Cry_Marshtomp::
	.incbin "sound/direct_sound_samples/cries/marshtomp.bin"

	.align 2
Cry_Swampert::
	.incbin "sound/direct_sound_samples/cries/swampert.bin"

	.align 2
Cry_Pelipper::
	.incbin "sound/direct_sound_samples/cries/pelipper.bin"

	.align 2
Cry_Wingull::
	.incbin "sound/direct_sound_samples/cries/wingull.bin"

	.align 2
Cry_Banette::
	.incbin "sound/direct_sound_samples/cries/banette.bin"

	.align 2
Cry_Shuppet::
	.incbin "sound/direct_sound_samples/cries/shuppet.bin"

	.align 2
Cry_Lotad::
	.incbin "sound/direct_sound_samples/cries/lotad.bin"

	.align 2
Cry_Lombre::
	.incbin "sound/direct_sound_samples/cries/lombre.bin"

	.align 2
Cry_Ludicolo::
	.incbin "sound/direct_sound_samples/cries/ludicolo.bin"

	.align 2
Cry_Seedot::
	.incbin "sound/direct_sound_samples/cries/seedot.bin"

	.align 2
Cry_Nuzleaf::
	.incbin "sound/direct_sound_samples/cries/nuzleaf.bin"

	.align 2
Cry_Shiftry::
	.incbin "sound/direct_sound_samples/cries/shiftry.bin"

	.align 2
Cry_Carvanha::
	.incbin "sound/direct_sound_samples/cries/carvanha.bin"

	.align 2
Cry_Wurmple::
	.incbin "sound/direct_sound_samples/cries/wurmple.bin"

	.align 2
Cry_Silcoon::
	.incbin "sound/direct_sound_samples/cries/silcoon.bin"

	.align 2
Cry_Beautifly::
	.incbin "sound/direct_sound_samples/cries/beautifly.bin"

	.align 2
Cry_Cascoon::
	.incbin "sound/direct_sound_samples/cries/cascoon.bin"

	.align 2
Cry_Dustox::
	.incbin "sound/direct_sound_samples/cries/dustox.bin"

	.align 2
Cry_Ralts::
	.incbin "sound/direct_sound_samples/cries/ralts.bin"

	.align 2
Cry_Kirlia::
	.incbin "sound/direct_sound_samples/cries/kirlia.bin"

	.align 2
Cry_Gardevoir::
	.incbin "sound/direct_sound_samples/cries/gardevoir.bin"

	.align 2
Cry_Slakoth::
	.incbin "sound/direct_sound_samples/cries/slakoth.bin"

	.align 2
Cry_Vigoroth::
	.incbin "sound/direct_sound_samples/cries/vigoroth.bin"

	.align 2
Cry_Slaking::
	.incbin "sound/direct_sound_samples/cries/slaking.bin"

	.align 2
Cry_Nincada::
	.incbin "sound/direct_sound_samples/cries/nincada.bin"

	.align 2
Cry_Ninjask::
	.incbin "sound/direct_sound_samples/cries/ninjask.bin"

	.align 2
Cry_Shedinja::
	.incbin "sound/direct_sound_samples/cries/shedinja.bin"

	.align 2
Cry_Makuhita::
	.incbin "sound/direct_sound_samples/cries/makuhita.bin"

	.align 2
Cry_Hariyama::
	.incbin "sound/direct_sound_samples/cries/hariyama.bin"

	.align 2
Cry_Nosepass::
	.incbin "sound/direct_sound_samples/cries/nosepass.bin"

	.align 2
Cry_Glalie::
	.incbin "sound/direct_sound_samples/cries/glalie.bin"

	.align 2
Cry_Plusle::
	.incbin "sound/direct_sound_samples/cries/plusle.bin"

	.align 2
Cry_Minun::
	.incbin "sound/direct_sound_samples/cries/minun.bin"

	.align 2
Cry_Surskit::
	.incbin "sound/direct_sound_samples/cries/surskit.bin"

	.align 2
Cry_Masquerain::
	.incbin "sound/direct_sound_samples/cries/masquerain.bin"

	.align 2
Cry_Skitty::
	.incbin "sound/direct_sound_samples/cries/skitty.bin"

	.align 2
Cry_Delcatty::
	.incbin "sound/direct_sound_samples/cries/delcatty.bin"

	.align 2
Cry_Gulpin::
	.incbin "sound/direct_sound_samples/cries/gulpin.bin"

	.align 2
Cry_Swalot::
	.incbin "sound/direct_sound_samples/cries/swalot.bin"

	.align 2
Cry_Numel::
	.incbin "sound/direct_sound_samples/cries/numel.bin"

	.align 2
Cry_Camerupt::
	.incbin "sound/direct_sound_samples/cries/camerupt.bin"

	.align 2
Cry_Barboach::
	.incbin "sound/direct_sound_samples/cries/barboach.bin"

	.align 2
Cry_Whiscash::
	.incbin "sound/direct_sound_samples/cries/whiscash.bin"

	.align 2
Cry_Corphish::
	.incbin "sound/direct_sound_samples/cries/corphish.bin"

	.align 2
Cry_Crawdaunt::
	.incbin "sound/direct_sound_samples/cries/crawdaunt.bin"

	.align 2
Cry_Spoink::
	.incbin "sound/direct_sound_samples/cries/spoink.bin"

	.align 2
Cry_Grumpig::
	.incbin "sound/direct_sound_samples/cries/grumpig.bin"

	.align 2
Cry_Trapinch::
	.incbin "sound/direct_sound_samples/cries/trapinch.bin"

	.align 2
Cry_Vibrava::
	.incbin "sound/direct_sound_samples/cries/vibrava.bin"

	.align 2
Cry_Flygon::
	.incbin "sound/direct_sound_samples/cries/flygon.bin"

	.align 2
Cry_Cacnea::
	.incbin "sound/direct_sound_samples/cries/cacnea.bin"

	.align 2
Cry_Cacturne::
	.incbin "sound/direct_sound_samples/cries/cacturne.bin"

	.align 2
Cry_Baltoy::
	.incbin "sound/direct_sound_samples/cries/baltoy.bin"

	.align 2
Cry_Claydol::
	.incbin "sound/direct_sound_samples/cries/claydol.bin"

	.align 2
Cry_Lunatone::
	.incbin "sound/direct_sound_samples/cries/lunatone.bin"

	.align 2
Cry_Solrock::
	.incbin "sound/direct_sound_samples/cries/solrock.bin"

	.align 2
Cry_Feebas::
	.incbin "sound/direct_sound_samples/cries/feebas.bin"

	.align 2
Cry_Milotic::
	.incbin "sound/direct_sound_samples/cries/milotic.bin"

	.align 2
Cry_Absol::
	.incbin "sound/direct_sound_samples/cries/absol.bin"

	.align 2
Cry_Meditite::
	.incbin "sound/direct_sound_samples/cries/meditite.bin"

	.align 2
Cry_Medicham::
	.incbin "sound/direct_sound_samples/cries/medicham.bin"

	.align 2
Cry_Spheal::
	.incbin "sound/direct_sound_samples/cries/spheal.bin"

	.align 2
Cry_Sealeo::
	.incbin "sound/direct_sound_samples/cries/sealeo.bin"

	.align 2
Cry_Walrein::
	.incbin "sound/direct_sound_samples/cries/walrein.bin"

	.align 2
Cry_Clamperl::
	.incbin "sound/direct_sound_samples/cries/clamperl.bin"

	.align 2
Cry_Huntail::
	.incbin "sound/direct_sound_samples/cries/huntail.bin"

	.align 2
Cry_Gorebyss::
	.incbin "sound/direct_sound_samples/cries/gorebyss.bin"

	.align 2
Cry_Lileep::
	.incbin "sound/direct_sound_samples/cries/lileep.bin"

	.align 2
Cry_Cradily::
	.incbin "sound/direct_sound_samples/cries/cradily.bin"

	.align 2
Cry_Anorith::
	.incbin "sound/direct_sound_samples/cries/anorith.bin"

	.align 2
Cry_Armaldo::
	.incbin "sound/direct_sound_samples/cries/armaldo.bin"

	.align 2
Cry_Beldum::
	.incbin "sound/direct_sound_samples/cries/beldum.bin"

	.align 2
Cry_Metang::
	.incbin "sound/direct_sound_samples/cries/metang.bin"

	.align 2
Cry_Metagross::
	.incbin "sound/direct_sound_samples/cries/metagross.bin"

	.align 2
Cry_Bagon::
	.incbin "sound/direct_sound_samples/cries/bagon.bin"

	.align 2
Cry_Shelgon::
	.incbin "sound/direct_sound_samples/cries/shelgon.bin"

	.align 2
Cry_Regirock::
	.incbin "sound/direct_sound_samples/cries/regirock.bin"

	.align 2
Cry_Regice::
	.incbin "sound/direct_sound_samples/cries/regice.bin"

	.align 2
Cry_Registeel::
	.incbin "sound/direct_sound_samples/cries/registeel.bin"

	.align 2
Cry_Castform::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Volbeat::
	.incbin "sound/direct_sound_samples/cries/volbeat.bin"

	.align 2
Cry_Illumise::
	.incbin "sound/direct_sound_samples/cries/illumise.bin"

	.align 2
Cry_Poochyena::
	.incbin "sound/direct_sound_samples/cries/poochyena.bin"

	.align 2
Cry_Mightyena::
	.incbin "sound/direct_sound_samples/cries/mightyena.bin"

	.align 2
Cry_Dusclops::
	.incbin "sound/direct_sound_samples/cries/dusclops.bin"

	.align 2
Cry_Sableye::
	.incbin "sound/direct_sound_samples/cries/sableye.bin"

	.align 2
Cry_Mawile::
	.incbin "sound/direct_sound_samples/cries/mawile.bin"

	.align 2
Cry_Aron::
	.incbin "sound/direct_sound_samples/cries/aron.bin"

	.align 2
Cry_Lairon::
	.incbin "sound/direct_sound_samples/cries/lairon.bin"

	.align 2
Cry_Aggron::
	.incbin "sound/direct_sound_samples/cries/aggron.bin"

	.align 2
Cry_Relicanth::
	.incbin "sound/direct_sound_samples/cries/relicanth.bin"

	.align 2
Cry_Luvdisc::
	.incbin "sound/direct_sound_samples/cries/luvdisc.bin"

	.align 2
Cry_Groudon::
	.incbin "sound/direct_sound_samples/cries/groudon.bin"

	.align 2
Cry_Kyogre::
	.incbin "sound/direct_sound_samples/cries/kyogre.bin"

	.align 2
Cry_Rayquaza::
	.incbin "sound/direct_sound_samples/cries/rayquaza.bin"

	.align 2
Cry_Salamence::
	.incbin "sound/direct_sound_samples/cries/salamence.bin"

	.align 2
Cry_Breloom::
	.incbin "sound/direct_sound_samples/cries/breloom.bin"

	.align 2
Cry_Shroomish::
	.incbin "sound/direct_sound_samples/cries/shroomish.bin"

	.align 2
Cry_Linoone::
	.incbin "sound/direct_sound_samples/cries/linoone.bin"

	.align 2
Cry_Tropius::
	.incbin "sound/direct_sound_samples/cries/tropius.bin"

	.align 2
Cry_Wailmer::
	.incbin "sound/direct_sound_samples/cries/wailmer.bin"

	.align 2
Cry_Zigzagoon::
	.incbin "sound/direct_sound_samples/cries/zigzagoon.bin"

	.align 2
Cry_Exploud::
	.incbin "sound/direct_sound_samples/cries/exploud.bin"

	.align 2
Cry_Loudred::
	.incbin "sound/direct_sound_samples/cries/loudred.bin"

	.align 2
Cry_Wailord::
	.incbin "sound/direct_sound_samples/cries/wailord.bin"

	.align 2
Cry_Whismur::
	.incbin "sound/direct_sound_samples/cries/whismur.bin"

	.align 2
Cry_Snorunt::
	.incbin "sound/direct_sound_samples/cries/snorunt.bin"

	.align 2
Cry_Latios::
	.incbin "sound/direct_sound_samples/cries/latios.bin"

	.align 2
Cry_Jirachi::
	.incbin "sound/direct_sound_samples/cries/jirachi.bin"

	.align 2
Cry_Deoxys::
	.incbin "sound/direct_sound_samples/cries/deoxys.bin"

	.align 2
Cry_Chimecho::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_unknown_18::
	.incbin "sound/direct_sound_samples/unknown_18.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_Phoneme_1::
	.incbin "sound/direct_sound_samples/phonemes/01.bin"

	.align 2
DirectSoundWaveData_Phoneme_2::
	.incbin "sound/direct_sound_samples/phonemes/02.bin"

	.align 2
DirectSoundWaveData_Phoneme_3::
	.incbin "sound/direct_sound_samples/phonemes/03.bin"

	.align 2
DirectSoundWaveData_Phoneme_4::
	.incbin "sound/direct_sound_samples/phonemes/04.bin"

	.align 2
DirectSoundWaveData_Phoneme_5::
	.incbin "sound/direct_sound_samples/phonemes/05.bin"

	.align 2
DirectSoundWaveData_Phoneme_6::
	.incbin "sound/direct_sound_samples/phonemes/06.bin"

	.align 2
DirectSoundWaveData_Phoneme_7::
	.incbin "sound/direct_sound_samples/phonemes/07.bin"

	.align 2
DirectSoundWaveData_Phoneme_8::
	.incbin "sound/direct_sound_samples/phonemes/08.bin"

	.align 2
DirectSoundWaveData_Phoneme_9::
	.incbin "sound/direct_sound_samples/phonemes/09.bin"

	.align 2
DirectSoundWaveData_Phoneme_10::
	.incbin "sound/direct_sound_samples/phonemes/10.bin"

	.align 2
DirectSoundWaveData_Phoneme_11::
	.incbin "sound/direct_sound_samples/phonemes/11.bin"

	.align 2
DirectSoundWaveData_Phoneme_12::
	.incbin "sound/direct_sound_samples/phonemes/12.bin"

	.align 2
DirectSoundWaveData_Phoneme_13::
	.incbin "sound/direct_sound_samples/phonemes/13.bin"

	.align 2
DirectSoundWaveData_Phoneme_14::
	.incbin "sound/direct_sound_samples/phonemes/14.bin"

	.align 2
DirectSoundWaveData_Phoneme_15::
	.incbin "sound/direct_sound_samples/phonemes/15.bin"

	.align 2
DirectSoundWaveData_Phoneme_16::
	.incbin "sound/direct_sound_samples/phonemes/16.bin"

	.align 2
DirectSoundWaveData_Phoneme_17::
	.incbin "sound/direct_sound_samples/phonemes/17.bin"

	.align 2
DirectSoundWaveData_Phoneme_18::
	.incbin "sound/direct_sound_samples/phonemes/18.bin"

	.align 2
DirectSoundWaveData_Phoneme_19::
	.incbin "sound/direct_sound_samples/phonemes/19.bin"

	.align 2
DirectSoundWaveData_Phoneme_20::
	.incbin "sound/direct_sound_samples/phonemes/20.bin"

	.align 2
DirectSoundWaveData_Phoneme_21::
	.incbin "sound/direct_sound_samples/phonemes/21.bin"

	.align 2
DirectSoundWaveData_Phoneme_22::
	.incbin "sound/direct_sound_samples/phonemes/22.bin"

	.align 2
DirectSoundWaveData_Phoneme_23::
	.incbin "sound/direct_sound_samples/phonemes/23.bin"

	.align 2
DirectSoundWaveData_Phoneme_24::
	.incbin "sound/direct_sound_samples/phonemes/24.bin"

	.align 2
DirectSoundWaveData_Phoneme_25::
	.incbin "sound/direct_sound_samples/phonemes/25.bin"

	.align 2
DirectSoundWaveData_Phoneme_26::
	.incbin "sound/direct_sound_samples/phonemes/26.bin"

	.align 2
DirectSoundWaveData_Phoneme_27::
	.incbin "sound/direct_sound_samples/phonemes/27.bin"

	.align 2
DirectSoundWaveData_Phoneme_28::
	.incbin "sound/direct_sound_samples/phonemes/28.bin"

	.align 2
DirectSoundWaveData_Phoneme_29::
	.incbin "sound/direct_sound_samples/phonemes/29.bin"

	.align 2
DirectSoundWaveData_Phoneme_30::
	.incbin "sound/direct_sound_samples/phonemes/30.bin"

	.align 2
DirectSoundWaveData_Phoneme_31::
	.incbin "sound/direct_sound_samples/phonemes/31.bin"

	.align 2
DirectSoundWaveData_Phoneme_32::
	.incbin "sound/direct_sound_samples/phonemes/32.bin"

	.align 2
DirectSoundWaveData_Phoneme_33::
	.incbin "sound/direct_sound_samples/phonemes/33.bin"

	.align 2
DirectSoundWaveData_Phoneme_34::
	.incbin "sound/direct_sound_samples/phonemes/34.bin"

	.align 2
DirectSoundWaveData_Phoneme_35::
	.incbin "sound/direct_sound_samples/phonemes/35.bin"

	.align 2
DirectSoundWaveData_Phoneme_36::
	.incbin "sound/direct_sound_samples/phonemes/36.bin"

	.align 2
DirectSoundWaveData_Phoneme_37::
	.incbin "sound/direct_sound_samples/phonemes/37.bin"

	.align 2
DirectSoundWaveData_Phoneme_38::
	.incbin "sound/direct_sound_samples/phonemes/38.bin"

	.align 2
DirectSoundWaveData_Phoneme_39::
	.incbin "sound/direct_sound_samples/phonemes/39.bin"

	.align 2
DirectSoundWaveData_Phoneme_40::
	.incbin "sound/direct_sound_samples/phonemes/40.bin"

	.align 2
DirectSoundWaveData_Phoneme_41::
	.incbin "sound/direct_sound_samples/phonemes/41.bin"

	.align 2
DirectSoundWaveData_Phoneme_42::
	.incbin "sound/direct_sound_samples/phonemes/42.bin"

	.align 2
DirectSoundWaveData_Phoneme_43::
	.incbin "sound/direct_sound_samples/phonemes/43.bin"

	.align 2
DirectSoundWaveData_Phoneme_44::
	.incbin "sound/direct_sound_samples/phonemes/44.bin"

	.align 2
DirectSoundWaveData_Phoneme_45::
	.incbin "sound/direct_sound_samples/phonemes/45.bin"

	.align 2
DirectSoundWaveData_Phoneme_46::
	.incbin "sound/direct_sound_samples/phonemes/46.bin"

	.align 2
DirectSoundWaveData_Phoneme_47::
	.incbin "sound/direct_sound_samples/phonemes/47.bin"

	.align 2
DirectSoundWaveData_Phoneme_48::
	.incbin "sound/direct_sound_samples/phonemes/48.bin"

	.align 2
DirectSoundWaveData_Phoneme_49::
	.incbin "sound/direct_sound_samples/phonemes/49.bin"

	.align 2
DirectSoundWaveData_Phoneme_50::
	.incbin "sound/direct_sound_samples/phonemes/50.bin"

	.align 2
DirectSoundWaveData_Phoneme_51::
	.incbin "sound/direct_sound_samples/phonemes/51.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88pro_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"

	.align 2
DirectSoundWaveData_puresquare_12::
	.incbin "sound/direct_sound_samples/puresquare_12.bin"

	.align 2
DirectSoundWaveData_puresquare_25::
	.incbin "sound/direct_sound_samples/puresquare_25.bin"

	.align 2
DirectSoundWaveData_puresquare_37::
	.incbin "sound/direct_sound_samples/puresquare_37.bin"

	.align 2
DirectSoundWaveData_puresquare_50::
	.incbin "sound/direct_sound_samples/puresquare_50.bin"

	.align 2
DirectSoundWaveData_purenoise::
	.incbin "sound/direct_sound_samples/purenoise.bin"

	.align 2
DirectSoundWaveData_dp_808snare_16::
	.incbin "sound/direct_sound_samples/dp_808snare_16.bin"

	.align 2
DirectSoundWaveData_dp_accordion_c1_16::
	.incbin "sound/direct_sound_samples/dp_accordion_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_accordion_c2_16::
	.incbin "sound/direct_sound_samples/dp_accordion_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_accordion_c3_16::
	.incbin "sound/direct_sound_samples/dp_accordion_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_accordion_c4_16::
	.incbin "sound/direct_sound_samples/dp_accordion_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_acgt_e1_16::
	.incbin "sound/direct_sound_samples/dp_acgt_e1_16.bin"

	.align 2
DirectSoundWaveData_dp_acgt_e2_16::
	.incbin "sound/direct_sound_samples/dp_acgt_e2_16.bin"

	.align 2
DirectSoundWaveData_dp_acgt_e3_16::
	.incbin "sound/direct_sound_samples/dp_acgt_e3_16.bin"

	.align 2
DirectSoundWaveData_dp_acgt_e4_16::
	.incbin "sound/direct_sound_samples/dp_acgt_e4_16.bin"

	.align 2
DirectSoundWaveData_dp_africa_dr_16::
	.incbin "sound/direct_sound_samples/dp_africa_dr_16.bin"

	.align 2
DirectSoundWaveData_dp_altosax_c3_16::
	.incbin "sound/direct_sound_samples/dp_altosax_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_bass2::
	.incbin "sound/direct_sound_samples/dp_bass2.bin"

	.align 2
DirectSoundWaveData_dp_bassdr1::
	.incbin "sound/direct_sound_samples/dp_bassdr1.bin"

	.align 2
DirectSoundWaveData_dp_bassdr1_16::
	.incbin "sound/direct_sound_samples/dp_bassdr1_16.bin"

	.align 2
DirectSoundWaveData_dp_bassdr2_16::
	.incbin "sound/direct_sound_samples/dp_bassdr2_16.bin"

	.align 2
DirectSoundWaveData_dp_bluesgt_a2_16::
	.incbin "sound/direct_sound_samples/dp_bluesgt_a2_16.bin"

	.align 2
DirectSoundWaveData_dp_cabassa_16::
	.incbin "sound/direct_sound_samples/dp_cabassa_16.bin"

	.align 2
DirectSoundWaveData_dp_castanet_22::
	.incbin "sound/direct_sound_samples/dp_castanet_22.bin"

	.align 2
DirectSoundWaveData_dp_cawbell_16::
	.incbin "sound/direct_sound_samples/dp_cawbell_16.bin"

	.align 2
DirectSoundWaveData_dp_china_cynbal::
	.incbin "sound/direct_sound_samples/dp_china_cynbal.bin"

	.align 2
DirectSoundWaveData_dp_clavi_c1_16::
	.incbin "sound/direct_sound_samples/dp_clavi_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_clavi_c2_16::
	.incbin "sound/direct_sound_samples/dp_clavi_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_clavi_c3_16::
	.incbin "sound/direct_sound_samples/dp_clavi_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_clean_gt_c1_16::
	.incbin "sound/direct_sound_samples/dp_clean_gt_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_clean_gt_c2_16::
	.incbin "sound/direct_sound_samples/dp_clean_gt_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_clean_gt_c3_16::
	.incbin "sound/direct_sound_samples/dp_clean_gt_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_closed_hihat_16::
	.incbin "sound/direct_sound_samples/dp_closed_hihat_16.bin"

	.align 2
DirectSoundWaveData_dp_closehight_16::
	.incbin "sound/direct_sound_samples/dp_closehight_16.bin"

	.align 2
DirectSoundWaveData_dp_cymbal1_16::
	.incbin "sound/direct_sound_samples/dp_cymbal1_16.bin"

	.align 2
DirectSoundWaveData_dp_dis_gt_c1_16::
	.incbin "sound/direct_sound_samples/dp_dis_gt_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_dis_gt_c2_16::
	.incbin "sound/direct_sound_samples/dp_dis_gt_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_dis_gt_c3_16::
	.incbin "sound/direct_sound_samples/dp_dis_gt_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_dis_gt_c4_16::
	.incbin "sound/direct_sound_samples/dp_dis_gt_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_disgt_b4_16::
	.incbin "sound/direct_sound_samples/dp_disgt_b4_16.bin"

	.align 2
DirectSoundWaveData_dp_disgt_c2_16::
	.incbin "sound/direct_sound_samples/dp_disgt_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_disgt_e1_16::
	.incbin "sound/direct_sound_samples/dp_disgt_e1_16.bin"

	.align 2
DirectSoundWaveData_dp_disgt_e3_16::
	.incbin "sound/direct_sound_samples/dp_disgt_e3_16.bin"

	.align 2
DirectSoundWaveData_dp_disgt_e4_16::
	.incbin "sound/direct_sound_samples/dp_disgt_e4_16.bin"

	.align 2
DirectSoundWaveData_dp_dragon_dr_16::
	.incbin "sound/direct_sound_samples/dp_dragon_dr_16.bin"

	.align 2
DirectSoundWaveData_dp_el_pia2_c3_22::
	.incbin "sound/direct_sound_samples/dp_el_pia2_c3_22.bin"

	.align 2
DirectSoundWaveData_dp_el_pia2_c4_22::
	.incbin "sound/direct_sound_samples/dp_el_pia2_c4_22.bin"

	.align 2
DirectSoundWaveData_dp_el_pia_c3_22::
	.incbin "sound/direct_sound_samples/dp_el_pia_c3_22.bin"

	.align 2
DirectSoundWaveData_dp_el_pia_c4_22::
	.incbin "sound/direct_sound_samples/dp_el_pia_c4_22.bin"

	.align 2
DirectSoundWaveData_dp_explosion::
	.incbin "sound/direct_sound_samples/dp_explosion.bin"

	.align 2
DirectSoundWaveData_dp_f_horn_c2_16::
	.incbin "sound/direct_sound_samples/dp_f_horn_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_f_horn_c4_16::
	.incbin "sound/direct_sound_samples/dp_f_horn_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_flute_c4_16::
	.incbin "sound/direct_sound_samples/dp_flute_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_flute_c5_16::
	.incbin "sound/direct_sound_samples/dp_flute_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_flute_c6_16::
	.incbin "sound/direct_sound_samples/dp_flute_c6_16.bin"

	.align 2
DirectSoundWaveData_dp_fretlessbass_d1_16::
	.incbin "sound/direct_sound_samples/dp_fretlessbass_d1_16.bin"

	.align 2
DirectSoundWaveData_dp_glocken_c6_16::
	.incbin "sound/direct_sound_samples/dp_glocken_c6_16.bin"

	.align 2
DirectSoundWaveData_dp_handclup1::
	.incbin "sound/direct_sound_samples/dp_handclup1.bin"

	.align 2
DirectSoundWaveData_dp_harmonica_c3_16::
	.incbin "sound/direct_sound_samples/dp_harmonica_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_harp_c3_16::
	.incbin "sound/direct_sound_samples/dp_harp_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_harp_c4_16::
	.incbin "sound/direct_sound_samples/dp_harp_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_harp_c5_16::
	.incbin "sound/direct_sound_samples/dp_harp_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_harp_c6_16::
	.incbin "sound/direct_sound_samples/dp_harp_c6_16.bin"

	.align 2
DirectSoundWaveData_dp_india_per_16::
	.incbin "sound/direct_sound_samples/dp_india_per_16.bin"

	.align 2
DirectSoundWaveData_dp_kaaroop_16::
	.incbin "sound/direct_sound_samples/dp_kaaroop_16.bin"

	.align 2
DirectSoundWaveData_dp_marin_c3_16::
	.incbin "sound/direct_sound_samples/dp_marin_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_marin_c4_16::
	.incbin "sound/direct_sound_samples/dp_marin_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_marin_c5_16::
	.incbin "sound/direct_sound_samples/dp_marin_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_merotim_c2_16::
	.incbin "sound/direct_sound_samples/dp_merotim_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_merotim_c3_16::
	.incbin "sound/direct_sound_samples/dp_merotim_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_mute_conga_16::
	.incbin "sound/direct_sound_samples/dp_mute_conga_16.bin"

	.align 2
DirectSoundWaveData_dp_oboe_c3_16::
	.incbin "sound/direct_sound_samples/dp_oboe_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_oct_g3_16::
	.incbin "sound/direct_sound_samples/dp_oct_g3_16.bin"

	.align 2
DirectSoundWaveData_dp_oct_snare_16::
	.incbin "sound/direct_sound_samples/dp_oct_snare_16.bin"

	.align 2
DirectSoundWaveData_dp_octhit_c2_16::
	.incbin "sound/direct_sound_samples/dp_octhit_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_octlow_cs2_16::
	.incbin "sound/direct_sound_samples/dp_octlow_cs2_16.bin"

	.align 2
DirectSoundWaveData_dp_octlowbra_b2_16::
	.incbin "sound/direct_sound_samples/dp_octlowbra_b2_16.bin"

	.align 2
DirectSoundWaveData_dp_open_hihat_16::
	.incbin "sound/direct_sound_samples/dp_open_hihat_16.bin"

	.align 2
DirectSoundWaveData_dp_openhight::
	.incbin "sound/direct_sound_samples/dp_openhight.bin"

	.align 2
DirectSoundWaveData_dp_org1_c2_16::
	.incbin "sound/direct_sound_samples/dp_org1_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_org1_c3_16::
	.incbin "sound/direct_sound_samples/dp_org1_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_org1_c4_16::
	.incbin "sound/direct_sound_samples/dp_org1_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_org1_c5_16::
	.incbin "sound/direct_sound_samples/dp_org1_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_org4_c3_16::
	.incbin "sound/direct_sound_samples/dp_org4_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_org4_c4_16::
	.incbin "sound/direct_sound_samples/dp_org4_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_org5_c3_16::
	.incbin "sound/direct_sound_samples/dp_org5_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_pedalhight::
	.incbin "sound/direct_sound_samples/dp_pedalhight.bin"

	.align 2
DirectSoundWaveData_dp_pic_g4_16::
	.incbin "sound/direct_sound_samples/dp_pic_g4_16.bin"

	.align 2
DirectSoundWaveData_dp_pic_g5_16::
	.incbin "sound/direct_sound_samples/dp_pic_g5_16.bin"

	.align 2
DirectSoundWaveData_dp_pickbass_e1_16::
	.incbin "sound/direct_sound_samples/dp_pickbass_e1_16.bin"

	.align 2
DirectSoundWaveData_dp_power_gt_b1_16::
	.incbin "sound/direct_sound_samples/dp_power_gt_b1_16.bin"

	.align 2
DirectSoundWaveData_dp_power_gt_e1_16::
	.incbin "sound/direct_sound_samples/dp_power_gt_e1_16.bin"

	.align 2
DirectSoundWaveData_dp_power_gt_e2_16::
	.incbin "sound/direct_sound_samples/dp_power_gt_e2_16.bin"

	.align 2
DirectSoundWaveData_dp_reverscyn_16::
	.incbin "sound/direct_sound_samples/dp_reverscyn_16.bin"

	.align 2
DirectSoundWaveData_dp_ridecap::
	.incbin "sound/direct_sound_samples/dp_ridecap.bin"

	.align 2
DirectSoundWaveData_dp_ridecynbal::
	.incbin "sound/direct_sound_samples/dp_ridecynbal.bin"

	.align 2
DirectSoundWaveData_dp_rim1_roop::
	.incbin "sound/direct_sound_samples/dp_rim1_roop.bin"

	.align 2
DirectSoundWaveData_dp_sheiker::
	.incbin "sound/direct_sound_samples/dp_sheiker.bin"

	.align 2
DirectSoundWaveData_dp_slapbass_c1_16::
	.incbin "sound/direct_sound_samples/dp_slapbass_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_slapbass_g1_16::
	.incbin "sound/direct_sound_samples/dp_slapbass_g1_16.bin"

	.align 2
DirectSoundWaveData_dp_sne1_roop::
	.incbin "sound/direct_sound_samples/dp_sne1_roop.bin"

	.align 2
DirectSoundWaveData_dp_sne2_loop::
	.incbin "sound/direct_sound_samples/dp_sne2_loop.bin"

	.align 2
DirectSoundWaveData_dp_sting_bass_e1_16::
	.incbin "sound/direct_sound_samples/dp_sting_bass_e1_16.bin"

	.align 2
DirectSoundWaveData_dp_strings_c1_16::
	.incbin "sound/direct_sound_samples/dp_strings_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_strings_c2_16::
	.incbin "sound/direct_sound_samples/dp_strings_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_strings_c3_16::
	.incbin "sound/direct_sound_samples/dp_strings_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_strings_c4_16::
	.incbin "sound/direct_sound_samples/dp_strings_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_c0_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_c0_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_c1_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_c2_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_c3_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_c4_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_c5_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_c6_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_c6_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_f4_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_f4_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_g1_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_g1_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_g3_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_g3_16.bin"

	.align 2
DirectSoundWaveData_dp_sy_clarinet_c3_16::
	.incbin "sound/direct_sound_samples/dp_sy_clarinet_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_synbass1_c2_16::
	.incbin "sound/direct_sound_samples/dp_synbass1_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_synbass2_c1_16::
	.incbin "sound/direct_sound_samples/dp_synbass2_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_synbass_c1_16::
	.incbin "sound/direct_sound_samples/dp_synbass_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_tambourine_16::
	.incbin "sound/direct_sound_samples/dp_tambourine_16.bin"

	.align 2
DirectSoundWaveData_dp_timpany_as_16::
	.incbin "sound/direct_sound_samples/dp_timpany_as_16.bin"

	.align 2
DirectSoundWaveData_dp_timpany_e_16::
	.incbin "sound/direct_sound_samples/dp_timpany_e_16.bin"

	.align 2
DirectSoundWaveData_dp_tom1_16::
	.incbin "sound/direct_sound_samples/dp_tom1_16.bin"

	.align 2
DirectSoundWaveData_dp_tom_16::
	.incbin "sound/direct_sound_samples/dp_tom_16.bin"

	.align 2
DirectSoundWaveData_dp_tp_b4_16::
	.incbin "sound/direct_sound_samples/dp_tp_b4_16.bin"

	.align 2
DirectSoundWaveData_dp_tp_cs3_16::
	.incbin "sound/direct_sound_samples/dp_tp_cs3_16.bin"

	.align 2
DirectSoundWaveData_dp_tp_cs4_16::
	.incbin "sound/direct_sound_samples/dp_tp_cs4_16.bin"

	.align 2
DirectSoundWaveData_dp_triangle_16::
	.incbin "sound/direct_sound_samples/dp_triangle_16.bin"

	.align 2
DirectSoundWaveData_dp_trombone_c2_16::
	.incbin "sound/direct_sound_samples/dp_trombone_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_trombone_c3_16::
	.incbin "sound/direct_sound_samples/dp_trombone_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_trombone_c4_16::
	.incbin "sound/direct_sound_samples/dp_trombone_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_tub_bell_c3_16::
	.incbin "sound/direct_sound_samples/dp_tub_bell_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_tub_bell_c4_16::
	.incbin "sound/direct_sound_samples/dp_tub_bell_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_tub_bell_c5_16::
	.incbin "sound/direct_sound_samples/dp_tub_bell_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_tub_bell_c6_16::
	.incbin "sound/direct_sound_samples/dp_tub_bell_c6_16.bin"

	.align 2
DirectSoundWaveData_dp_tuba_c1_22::
	.incbin "sound/direct_sound_samples/dp_tuba_c1_22.bin"

	.align 2
DirectSoundWaveData_dp_tuba_c2_22::
	.incbin "sound/direct_sound_samples/dp_tuba_c2_22.bin"

	.align 2
DirectSoundWaveData_dp_vibra_c1_16::
	.incbin "sound/direct_sound_samples/dp_vibra_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_vibra_c2_16::
	.incbin "sound/direct_sound_samples/dp_vibra_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_vibra_c3_16::
	.incbin "sound/direct_sound_samples/dp_vibra_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_vibra_c4_16::
	.incbin "sound/direct_sound_samples/dp_vibra_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_vibra_c5_16::
	.incbin "sound/direct_sound_samples/dp_vibra_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_vibra_c6_16::
	.incbin "sound/direct_sound_samples/dp_vibra_c6_16.bin"

	.align 2
DirectSoundWaveData_dp_violin_c1_16::
	.incbin "sound/direct_sound_samples/dp_violin_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_violin_c3_16::
	.incbin "sound/direct_sound_samples/dp_violin_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_violin_c4_16::
	.incbin "sound/direct_sound_samples/dp_violin_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_violin_c5_16::
	.incbin "sound/direct_sound_samples/dp_violin_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_whistle_c5_16::
	.incbin "sound/direct_sound_samples/dp_whistle_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_woodbass_d3_16::
	.incbin "sound/direct_sound_samples/dp_woodbass_d3_16.bin"

	.align 2
DirectSoundWaveData_dp_woodbass_g1_16::
	.incbin "sound/direct_sound_samples/dp_woodbass_g1_16.bin"

	.align 2
DirectSoundWaveData_dp_woodbass_gs2_16::
	.incbin "sound/direct_sound_samples/dp_woodbass_gs2_16.bin"

	.align 2
DirectSoundWaveData_dp_woodblock_16::
	.incbin "sound/direct_sound_samples/dp_woodblock_16.bin"

	.align 2
DirectSoundWaveData_dp_woodpat_c4_16::
	.incbin "sound/direct_sound_samples/dp_woodpat_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_xylphone_c2_16::
	.incbin "sound/direct_sound_samples/dp_xylphone_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_xylphone_c3_16::
	.incbin "sound/direct_sound_samples/dp_xylphone_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_xylphone_c4_16::
	.incbin "sound/direct_sound_samples/dp_xylphone_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_xylphone_c5_16::
	.incbin "sound/direct_sound_samples/dp_xylphone_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_xylphone_c6_16::
	.incbin "sound/direct_sound_samples/dp_xylphone_c6_16.bin"

	.align 2
DirectSoundWaveData_dp_synthkick::
	.incbin "sound/direct_sound_samples/dp_synthkick.bin"

	.align 2
DirectSoundWaveData_dp_synthsnare::
	.incbin "sound/direct_sound_samples/dp_synthsnare.bin"

	.align 2
DirectSoundWaveData_dp_basschoir36::
	.incbin "sound/direct_sound_samples/dp_basschoir36.bin"

	.align 2
DirectSoundWaveData_dp_tenorchoir48::
	.incbin "sound/direct_sound_samples/dp_tenorchoir48.bin"

	.align 2
DirectSoundWaveData_dp_sopranochoir60::
	.incbin "sound/direct_sound_samples/dp_sopranochoir60.bin"

	.align 2
DirectSoundWaveData_dp_orchhitmajor60::
	.incbin "sound/direct_sound_samples/dp_orchhitmajor60.bin"

	.align 2
DirectSoundWaveData_dp_orchhitminor60::
	.incbin "sound/direct_sound_samples/dp_orchhitminor60.bin"

	.align 2
DirectSoundWaveData_dp_sawtoothlead60::
	.incbin "sound/direct_sound_samples/dp_sawtoothlead60.bin"

	.align 2
DirectSoundWaveData_dp_banjo48::
	.incbin "sound/direct_sound_samples/dp_banjo48.bin"

	.align 2
DirectSoundWaveData_dp_banjo60::
	.incbin "sound/direct_sound_samples/dp_banjo60.bin"

	.align 2
DirectSoundWaveData_dp_trinitypiano36::
	.incbin "sound/direct_sound_samples/dp_trinitypiano36.bin"

	.align 2
DirectSoundWaveData_dp_trinitypiano48::
	.incbin "sound/direct_sound_samples/dp_trinitypiano48.bin"

	.align 2
DirectSoundWaveData_dp_trinitypiano60::
	.incbin "sound/direct_sound_samples/dp_trinitypiano60.bin"

	.align 2
DirectSoundWaveData_dp_trinitypiano72::
	.incbin "sound/direct_sound_samples/dp_trinitypiano72.bin"

	.align 2
DirectSoundWaveData_dp_fretnoise60::
	.incbin "sound/direct_sound_samples/dp_fretnoise60.bin"

	.align 2
DirectSoundWaveData_dp_eternaguitar36::
	.incbin "sound/direct_sound_samples/dp_eternaguitar36.bin"

	.align 2
DirectSoundWaveData_dp_spearpillarwind60::
	.incbin "sound/direct_sound_samples/dp_spearpillarwind60.bin"

	.align 2
DirectSoundWaveData_dp_016bongo::
	.incbin "sound/direct_sound_samples/dp_016bongo.bin"

	.align 2
DirectSoundWaveData_dp_053clap::
	.incbin "sound/direct_sound_samples/dp_053clap.bin"

	.align 2
DirectSoundWaveData_dp_060conga::
	.incbin "sound/direct_sound_samples/dp_060conga.bin"

	.align 2
DirectSoundWaveData_dp_062sleigh::
	.incbin "sound/direct_sound_samples/dp_062sleigh.bin"

	.align 2
DirectSoundWaveData_dp_093snare::
	.incbin "sound/direct_sound_samples/dp_093snare.bin"

	.align 2
DirectSoundWaveData_pl_musicbox62::
	.incbin "sound/direct_sound_samples/pl_musicbox62.bin"

	.align 2
DirectSoundWaveData_pl_musicbox79::
	.incbin "sound/direct_sound_samples/pl_musicbox79.bin"

	.align 2
DirectSoundWaveData_hg_000uprigc2::
	.incbin "sound/direct_sound_samples/hg_000uprigc2.bin"

	.align 2
DirectSoundWaveData_hg_001uprigc3::
	.incbin "sound/direct_sound_samples/hg_001uprigc3.bin"

	.align 2
DirectSoundWaveData_hg_002accorc3::
	.incbin "sound/direct_sound_samples/hg_002accorc3.bin"

	.align 2
DirectSoundWaveData_hg_003accorc4::
	.incbin "sound/direct_sound_samples/hg_003accorc4.bin"

	.align 2
DirectSoundWaveData_hg_004accorc5::
	.incbin "sound/direct_sound_samples/hg_004accorc5.bin"

	.align 2
DirectSoundWaveData_hg_005pnoffc4::
	.incbin "sound/direct_sound_samples/hg_005pnoffc4.bin"

	.align 2
DirectSoundWaveData_hg_006pnoffc5::
	.incbin "sound/direct_sound_samples/hg_006pnoffc5.bin"

	.align 2
DirectSoundWaveData_hg_010bsna3::
	.incbin "sound/direct_sound_samples/hg_010bsna3.bin"

	.align 2
DirectSoundWaveData_hg_011bsnc3::
	.incbin "sound/direct_sound_samples/hg_011bsnc3.bin"

	.align 2
DirectSoundWaveData_hg_012bsne2::
	.incbin "sound/direct_sound_samples/hg_012bsne2.bin"

	.align 2
DirectSoundWaveData_hg_014fhsolob4::
	.incbin "sound/direct_sound_samples/hg_014fhsolob4.bin"

	.align 2
DirectSoundWaveData_hg_015fhsolod4::
	.incbin "sound/direct_sound_samples/hg_015fhsolod4.bin"

	.align 2
DirectSoundWaveData_hg_016fhsolof3::
	.incbin "sound/direct_sound_samples/hg_016fhsolof3.bin"

	.align 2
DirectSoundWaveData_hg_019celloc4::
	.incbin "sound/direct_sound_samples/hg_019celloc4.bin"

	.align 2
DirectSoundWaveData_hg_020celloe3::
	.incbin "sound/direct_sound_samples/hg_020celloe3.bin"

	.align 2
DirectSoundWaveData_hg_021cellog2::
	.incbin "sound/direct_sound_samples/hg_021cellog2.bin"

	.align 2
DirectSoundWaveData_hg_022china::
	.incbin "sound/direct_sound_samples/hg_022china.bin"

	.align 2
DirectSoundWaveData_hg_023claric5::
	.incbin "sound/direct_sound_samples/hg_023claric5.bin"

	.align 2
DirectSoundWaveData_hg_024clarie4::
	.incbin "sound/direct_sound_samples/hg_024clarie4.bin"

	.align 2
DirectSoundWaveData_hg_025clarig3::
	.incbin "sound/direct_sound_samples/hg_025clarig3.bin"

	.align 2
DirectSoundWaveData_hg_027cleanc5::
	.incbin "sound/direct_sound_samples/hg_027cleanc5.bin"

	.align 2
DirectSoundWaveData_hg_028cleane4::
	.incbin "sound/direct_sound_samples/hg_028cleane4.bin"

	.align 2
DirectSoundWaveData_hg_029cleang2::
	.incbin "sound/direct_sound_samples/hg_029cleang2.bin"

	.align 2
DirectSoundWaveData_hg_030cleang3::
	.incbin "sound/direct_sound_samples/hg_030cleang3.bin"

	.align 2
DirectSoundWaveData_hg_031cowbl::
	.incbin "sound/direct_sound_samples/hg_031cowbl.bin"

	.align 2
DirectSoundWaveData_hg_032crash::
	.incbin "sound/direct_sound_samples/hg_032crash.bin"

	.align 2
DirectSoundWaveData_hg_033orccym::
	.incbin "sound/direct_sound_samples/hg_033orccym.bin"

	.align 2
DirectSoundWaveData_hg_038drawbc3::
	.incbin "sound/direct_sound_samples/hg_038drawbc3.bin"

	.align 2
DirectSoundWaveData_hg_039drawbc4::
	.incbin "sound/direct_sound_samples/hg_039drawbc4.bin"

	.align 2
DirectSoundWaveData_hg_040drawbc5::
	.incbin "sound/direct_sound_samples/hg_040drawbc5.bin"

	.align 2
DirectSoundWaveData_hg_041ampega2::
	.incbin "sound/direct_sound_samples/hg_041ampega2.bin"

	.align 2
DirectSoundWaveData_hg_042ampega3::
	.incbin "sound/direct_sound_samples/hg_042ampega3.bin"

	.align 2
DirectSoundWaveData_hg_043rhodc4::
	.incbin "sound/direct_sound_samples/hg_043rhodc4.bin"

	.align 2
DirectSoundWaveData_hg_044rhodc5::
	.incbin "sound/direct_sound_samples/hg_044rhodc5.bin"

	.align 2
DirectSoundWaveData_hg_046fhnsb4::
	.incbin "sound/direct_sound_samples/hg_046fhnsb4.bin"

	.align 2
DirectSoundWaveData_hg_047fhnsd4::
	.incbin "sound/direct_sound_samples/hg_047fhnsd4.bin"

	.align 2
DirectSoundWaveData_hg_048fhnsf3::
	.incbin "sound/direct_sound_samples/hg_048fhnsf3.bin"

	.align 2
DirectSoundWaveData_hg_049glocknc4::
	.incbin "sound/direct_sound_samples/hg_049glocknc4.bin"

	.align 2
DirectSoundWaveData_hg_050glocknc5::
	.incbin "sound/direct_sound_samples/hg_050glocknc5.bin"

	.align 2
DirectSoundWaveData_hg_051pnoc2::
	.incbin "sound/direct_sound_samples/hg_051pnoc2.bin"

	.align 2
DirectSoundWaveData_hg_052pnoc3::
	.incbin "sound/direct_sound_samples/hg_052pnoc3.bin"

	.align 2
DirectSoundWaveData_hg_053pnoc4::
	.incbin "sound/direct_sound_samples/hg_053pnoc4.bin"

	.align 2
DirectSoundWaveData_hg_054pnoc5::
	.incbin "sound/direct_sound_samples/hg_054pnoc5.bin"

	.align 2
DirectSoundWaveData_hg_055pnoc6::
	.incbin "sound/direct_sound_samples/hg_055pnoc6.bin"

	.align 2
DirectSoundWaveData_hg_058harpc3::
	.incbin "sound/direct_sound_samples/hg_058harpc3.bin"

	.align 2
DirectSoundWaveData_hg_059harpc4::
	.incbin "sound/direct_sound_samples/hg_059harpc4.bin"

	.align 2
DirectSoundWaveData_hg_060harpc5::
	.incbin "sound/direct_sound_samples/hg_060harpc5.bin"

	.align 2
DirectSoundWaveData_hg_062chh::
	.incbin "sound/direct_sound_samples/hg_062chh.bin"

	.align 2
DirectSoundWaveData_hg_063ohh::
	.incbin "sound/direct_sound_samples/hg_063ohh.bin"

	.align 2
DirectSoundWaveData_hg_065kotoa4::
	.incbin "sound/direct_sound_samples/hg_065kotoa4.bin"

	.align 2
DirectSoundWaveData_hg_066kotoc4::
	.incbin "sound/direct_sound_samples/hg_066kotoc4.bin"

	.align 2
DirectSoundWaveData_hg_067kotoe3::
	.incbin "sound/direct_sound_samples/hg_067kotoe3.bin"

	.align 2
DirectSoundWaveData_hg_068marimc4::
	.incbin "sound/direct_sound_samples/hg_068marimc4.bin"

	.align 2
DirectSoundWaveData_hg_069marimc5::
	.incbin "sound/direct_sound_samples/hg_069marimc5.bin"

	.align 2
DirectSoundWaveData_hg_070marimc6::
	.incbin "sound/direct_sound_samples/hg_070marimc6.bin"

	.align 2
DirectSoundWaveData_hg_071musboxc4::
	.incbin "sound/direct_sound_samples/hg_071musboxc4.bin"

	.align 2
DirectSoundWaveData_hg_072musboxc5::
	.incbin "sound/direct_sound_samples/hg_072musboxc5.bin"

	.align 2
DirectSoundWaveData_hg_073musboxc6::
	.incbin "sound/direct_sound_samples/hg_073musboxc6.bin"

	.align 2
DirectSoundWaveData_hg_075nylonc5::
	.incbin "sound/direct_sound_samples/hg_075nylonc5.bin"

	.align 2
DirectSoundWaveData_hg_076nylone4::
	.incbin "sound/direct_sound_samples/hg_076nylone4.bin"

	.align 2
DirectSoundWaveData_hg_077nylong2::
	.incbin "sound/direct_sound_samples/hg_077nylong2.bin"

	.align 2
DirectSoundWaveData_hg_078nylong3::
	.incbin "sound/direct_sound_samples/hg_078nylong3.bin"

	.align 2
DirectSoundWaveData_hg_079oboea5::
	.incbin "sound/direct_sound_samples/hg_079oboea5.bin"

	.align 2
DirectSoundWaveData_hg_080oboec5::
	.incbin "sound/direct_sound_samples/hg_080oboec5.bin"

	.align 2
DirectSoundWaveData_hg_081oboee4::
	.incbin "sound/direct_sound_samples/hg_081oboee4.bin"

	.align 2
DirectSoundWaveData_hg_082octpnoc2::
	.incbin "sound/direct_sound_samples/hg_082octpnoc2.bin"

	.align 2
DirectSoundWaveData_hg_083octpnoc3::
	.incbin "sound/direct_sound_samples/hg_083octpnoc3.bin"

	.align 2
DirectSoundWaveData_hg_084octpnoc4::
	.incbin "sound/direct_sound_samples/hg_084octpnoc4.bin"

	.align 2
DirectSoundWaveData_hg_085octpnoc5::
	.incbin "sound/direct_sound_samples/hg_085octpnoc5.bin"

	.align 2
DirectSoundWaveData_hg_086orchitc4::
	.incbin "sound/direct_sound_samples/hg_086orchitc4.bin"

	.align 2
DirectSoundWaveData_hg_087orchitc5::
	.incbin "sound/direct_sound_samples/hg_087orchitc5.bin"

	.align 2
DirectSoundWaveData_hg_088orchitc6::
	.incbin "sound/direct_sound_samples/hg_088orchitc6.bin"

	.align 2
DirectSoundWaveData_hg_089orchitg5::
	.incbin "sound/direct_sound_samples/hg_089orchitg5.bin"

	.align 2
DirectSoundWaveData_hg_091jazorgc3::
	.incbin "sound/direct_sound_samples/hg_091jazorgc3.bin"

	.align 2
DirectSoundWaveData_hg_092jazorgc4::
	.incbin "sound/direct_sound_samples/hg_092jazorgc4.bin"

	.align 2
DirectSoundWaveData_hg_093jazorgc5::
	.incbin "sound/direct_sound_samples/hg_093jazorgc5.bin"

	.align 2
DirectSoundWaveData_hg_094flt1a4::
	.incbin "sound/direct_sound_samples/hg_094flt1a4.bin"

	.align 2
DirectSoundWaveData_hg_095flt1c4::
	.incbin "sound/direct_sound_samples/hg_095flt1c4.bin"

	.align 2
DirectSoundWaveData_hg_096flt1c6::
	.incbin "sound/direct_sound_samples/hg_096flt1c6.bin"

	.align 2
DirectSoundWaveData_hg_097flt1f5::
	.incbin "sound/direct_sound_samples/hg_097flt1f5.bin"

	.align 2
DirectSoundWaveData_hg_098pizza4::
	.incbin "sound/direct_sound_samples/hg_098pizza4.bin"

	.align 2
DirectSoundWaveData_hg_099pizzc4::
	.incbin "sound/direct_sound_samples/hg_099pizzc4.bin"

	.align 2
DirectSoundWaveData_hg_100pizze3::
	.incbin "sound/direct_sound_samples/hg_100pizze3.bin"

	.align 2
DirectSoundWaveData_hg_101pizzf5::
	.incbin "sound/direct_sound_samples/hg_101pizzf5.bin"

	.align 2
DirectSoundWaveData_hg_102pizzg2::
	.incbin "sound/direct_sound_samples/hg_102pizzg2.bin"

	.align 2
DirectSoundWaveData_hg_114splash::
	.incbin "sound/direct_sound_samples/hg_114splash.bin"

	.align 2
DirectSoundWaveData_hg_115martinc5::
	.incbin "sound/direct_sound_samples/hg_115martinc5.bin"

	.align 2
DirectSoundWaveData_hg_116martine4::
	.incbin "sound/direct_sound_samples/hg_116martine4.bin"

	.align 2
DirectSoundWaveData_hg_117marting2::
	.incbin "sound/direct_sound_samples/hg_117marting2.bin"

	.align 2
DirectSoundWaveData_hg_118marting3::
	.incbin "sound/direct_sound_samples/hg_118marting3.bin"

	.align 2
DirectSoundWaveData_hg_119str1a4::
	.incbin "sound/direct_sound_samples/hg_119str1a4.bin"

	.align 2
DirectSoundWaveData_hg_120str1c4::
	.incbin "sound/direct_sound_samples/hg_120str1c4.bin"

	.align 2
DirectSoundWaveData_hg_121str1c6::
	.incbin "sound/direct_sound_samples/hg_121str1c6.bin"

	.align 2
DirectSoundWaveData_hg_122str1f5::
	.incbin "sound/direct_sound_samples/hg_122str1f5.bin"

	.align 2
DirectSoundWaveData_hg_123elastkc2::
	.incbin "sound/direct_sound_samples/hg_123elastkc2.bin"

	.align 2
DirectSoundWaveData_hg_124elastkc3::
	.incbin "sound/direct_sound_samples/hg_124elastkc3.bin"

	.align 2
DirectSoundWaveData_hg_125squarc4::
	.incbin "sound/direct_sound_samples/hg_125squarc4.bin"

	.align 2
DirectSoundWaveData_hg_126squarc5::
	.incbin "sound/direct_sound_samples/hg_126squarc5.bin"

	.align 2
DirectSoundWaveData_hg_127squarc6::
	.incbin "sound/direct_sound_samples/hg_127squarc6.bin"

	.align 2
DirectSoundWaveData_hg_128jdruml::
	.incbin "sound/direct_sound_samples/hg_128jdruml.bin"

	.align 2
DirectSoundWaveData_hg_129jdrumm::
	.incbin "sound/direct_sound_samples/hg_129jdrumm.bin"

	.align 2
DirectSoundWaveData_hg_130jdrumh::
	.incbin "sound/direct_sound_samples/hg_130jdrumh.bin"

	.align 2
DirectSoundWaveData_hg_132timpc4::
	.incbin "sound/direct_sound_samples/hg_132timpc4.bin"

	.align 2
DirectSoundWaveData_hg_133timpg3::
	.incbin "sound/direct_sound_samples/hg_133timpg3.bin"

	.align 2
DirectSoundWaveData_hg_134timpg4::
	.incbin "sound/direct_sound_samples/hg_134timpg4.bin"

	.align 2
DirectSoundWaveData_hg_135tom::
	.incbin "sound/direct_sound_samples/hg_135tom.bin"

	.align 2
DirectSoundWaveData_hg_136tom::
	.incbin "sound/direct_sound_samples/hg_136tom.bin"

	.align 2
DirectSoundWaveData_hg_137tom::
	.incbin "sound/direct_sound_samples/hg_137tom.bin"

	.align 2
DirectSoundWaveData_hg_138tom::
	.incbin "sound/direct_sound_samples/hg_138tom.bin"

	.align 2
DirectSoundWaveData_hg_140tbnc4::
	.incbin "sound/direct_sound_samples/hg_140tbnc4.bin"

	.align 2
DirectSoundWaveData_hg_141tbne3::
	.incbin "sound/direct_sound_samples/hg_141tbne3.bin"

	.align 2
DirectSoundWaveData_hg_142tbng2::
	.incbin "sound/direct_sound_samples/hg_142tbng2.bin"

	.align 2
DirectSoundWaveData_hg_143tpta4::
	.incbin "sound/direct_sound_samples/hg_143tpta4.bin"

	.align 2
DirectSoundWaveData_hg_144tptc4::
	.incbin "sound/direct_sound_samples/hg_144tptc4.bin"

	.align 2
DirectSoundWaveData_hg_145tptg5::
	.incbin "sound/direct_sound_samples/hg_145tptg5.bin"

	.align 2
DirectSoundWaveData_hg_146tbellc5::
	.incbin "sound/direct_sound_samples/hg_146tbellc5.bin"

	.align 2
DirectSoundWaveData_hg_147tbellg4::
	.incbin "sound/direct_sound_samples/hg_147tbellg4.bin"

	.align 2
DirectSoundWaveData_hg_148vibrc4::
	.incbin "sound/direct_sound_samples/hg_148vibrc4.bin"

	.align 2
DirectSoundWaveData_hg_149vibrc5::
	.incbin "sound/direct_sound_samples/hg_149vibrc5.bin"

	.align 2
DirectSoundWaveData_hg_150violna5::
	.incbin "sound/direct_sound_samples/hg_150violna5.bin"

	.align 2
DirectSoundWaveData_hg_151violnc5::
	.incbin "sound/direct_sound_samples/hg_151violnc5.bin"

	.align 2
DirectSoundWaveData_hg_152violne4::
	.incbin "sound/direct_sound_samples/hg_152violne4.bin"

	.align 2
DirectSoundWaveData_hg_155xylo1a4::
	.incbin "sound/direct_sound_samples/hg_155xylo1a4.bin"

	.align 2
DirectSoundWaveData_hg_156xylo1c4::
	.incbin "sound/direct_sound_samples/hg_156xylo1c4.bin"

	.align 2
DirectSoundWaveData_hg_157xylo1f5::
	.incbin "sound/direct_sound_samples/hg_157xylo1f5.bin"

	.align 2
DirectSoundWaveData_hg_shamisend3::
	.incbin "sound/direct_sound_samples/hg_shamisend3.bin"

	.align 2
DirectSoundWaveData_hg_shamisenas3::
	.incbin "sound/direct_sound_samples/hg_shamisenas3.bin"

	.align 2
DirectSoundWaveData_hg_shamiseng4::
	.incbin "sound/direct_sound_samples/hg_shamiseng4.bin"

	.align 2
DirectSoundWaveData_hg_pno4c2::
	.incbin "sound/direct_sound_samples/hg_pno4c2.bin"

	.align 2
DirectSoundWaveData_hg_pno4a2::
	.incbin "sound/direct_sound_samples/hg_pno4a2.bin"

	.align 2
DirectSoundWaveData_hg_pno4f3::
	.incbin "sound/direct_sound_samples/hg_pno4f3.bin"

	.align 2
DirectSoundWaveData_hg_pno4d4::
	.incbin "sound/direct_sound_samples/hg_pno4d4.bin"

	.align 2
DirectSoundWaveData_hg_pno4b4::
	.incbin "sound/direct_sound_samples/hg_pno4b4.bin"

	.align 2
DirectSoundWaveData_hg_pno4g5::
	.incbin "sound/direct_sound_samples/hg_pno4g5.bin"

	.align 2
DirectSoundWaveData_hg_pno4e6::
	.incbin "sound/direct_sound_samples/hg_pno4e6.bin"

	.align 2
DirectSoundWaveData_hg_hyoshigi::
	.incbin "sound/direct_sound_samples/hg_hyoshigi.bin"

	.align 2
DirectSoundWaveData_hg_kodaiko::
	.incbin "sound/direct_sound_samples/hg_kodaiko.bin"

	.align 2
DirectSoundWaveData_hg_tsuzumi::
	.incbin "sound/direct_sound_samples/hg_tsuzumi.bin"

	.align 2
DirectSoundWaveData_hg_jinglebell::
	.incbin "sound/direct_sound_samples/hg_jinglebell.bin"

	.align 2
DirectSoundWaveData_hg_hoohclap::
	.incbin "sound/direct_sound_samples/hg_hoohclap.bin"

	.align 2
DirectSoundWaveData_hg_choirc5::
	.incbin "sound/direct_sound_samples/hg_choirc5.bin"

	.align 2
DirectSoundWaveData_mm_acoustic_guitar_high::
	.incbin "sound/direct_sound_samples/mm/Acoustic_Guitar_High.bin"

	.align 2
DirectSoundWaveData_mm_acoustic_guitar_low::
	.incbin "sound/direct_sound_samples/mm/Acoustic_Guitar_Low.bin"

	.align 2
DirectSoundWaveData_mm_bassoon_high::
	.incbin "sound/direct_sound_samples/mm/Bassoon_High.bin"

	.align 2
DirectSoundWaveData_mm_bassoon_low::
	.incbin "sound/direct_sound_samples/mm/Bassoon_Low.bin"

	.align 2
DirectSoundWaveData_mm_dulcimer_high::
	.incbin "sound/direct_sound_samples/mm/Dulcimer_High.bin"

	.align 2
DirectSoundWaveData_mm_dulcimer_low::
	.incbin "sound/direct_sound_samples/mm/Dulcimer_Low.bin"

	.align 2
DirectSoundWaveData_mm_elves::
	.incbin "sound/direct_sound_samples/mm/Elves.bin"

	.align 2
DirectSoundWaveData_mm_female_choir_high::
	.incbin "sound/direct_sound_samples/mm/Female_Choir_High.bin"

	.align 2
DirectSoundWaveData_mm_female_choir_low::
	.incbin "sound/direct_sound_samples/mm/Female_Choir_Low.bin"

	.align 2
DirectSoundWaveData_mm_harmonica::
	.incbin "sound/direct_sound_samples/mm/Harmonica.bin"

	.align 2
DirectSoundWaveData_mm_male_choir_high::
	.incbin "sound/direct_sound_samples/mm/Male_Choir_High.bin"

	.align 2
DirectSoundWaveData_mm_male_choir_low::
	.incbin "sound/direct_sound_samples/mm/Male_Choir_Low.bin"

	.align 2
DirectSoundWaveData_mm_oboe::
	.incbin "sound/direct_sound_samples/mm/Oboe.bin"

	.align 2
DirectSoundWaveData_mm_ocarina::
	.incbin "sound/direct_sound_samples/mm/Ocarina.bin"

	.align 2
DirectSoundWaveData_mm_piccolo::
	.incbin "sound/direct_sound_samples/mm/Piccolo.bin"

	.align 2
DirectSoundWaveData_mm_strings_high::
	.incbin "sound/direct_sound_samples/mm/Strings_High.bin"

	.align 2
DirectSoundWaveData_mm_strings_low::
	.incbin "sound/direct_sound_samples/mm/Strings_Low.bin"

	.align 2
DirectSoundWaveData_mm_strings_mid::
	.incbin "sound/direct_sound_samples/mm/Strings_Mid.bin"

	.align 2
DirectSoundWaveData_mm_tambourine_1::
	.incbin "sound/direct_sound_samples/mm/Tambourine_1.bin"

	.align 2
DirectSoundWaveData_mm_tambourine_2::
	.incbin "sound/direct_sound_samples/mm/Tambourine_2.bin"

	.align 2
DirectSoundWaveData_mm_tambourine_3::
	.incbin "sound/direct_sound_samples/mm/Tambourine_3.bin"

	.align 2
DirectSoundWaveData_mm_wind::
	.incbin "sound/direct_sound_samples/mm/Wind.bin"

	.align 2
DirectSoundWaveData_sa2_1::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__organ_3_charselect_1.bin"

	.align 2
DirectSoundWaveData_sa2_2::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__organ_3_charselect_2.bin"

	.align 2
DirectSoundWaveData_sa2_3::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__pr_d__019_organ_3__1.bin"

	.align 2
DirectSoundWaveData_sa2_4::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__pr_d__019_organ_3__2.bin"

	.align 2
DirectSoundWaveData_sa2_5::
	.incbin "sound/direct_sound_samples/sa2/korg_trinity__stereo_brass_1.bin"

	.align 2
DirectSoundWaveData_sa2_6::
	.incbin "sound/direct_sound_samples/sa2/korg_trinity__synth_brass2_1.bin"

	.align 2
DirectSoundWaveData_sa2_7::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__pr_d__019_organ_3__3.bin"

	.align 2
DirectSoundWaveData_sa2_8::
	.incbin "sound/direct_sound_samples/sa2/unknown_8ade918.bin"

	.align 2
DirectSoundWaveData_sa2_9::
	.incbin "sound/direct_sound_samples/sa2/korg_trinity__stereo_brass_2.bin"

	.align 2
DirectSoundWaveData_sa2_10::
	.incbin "sound/direct_sound_samples/sa2/korg_trinity__synth_brass2_2.bin"

	.align 2
DirectSoundWaveData_sa2_11::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__pr_d__019_organ_3__4.bin"

	.align 2
DirectSoundWaveData_sa2_12::
	.incbin "sound/direct_sound_samples/sa2/roland_sr_jv80_02__bassoon_1.bin"

	.align 2
DirectSoundWaveData_sa2_13::
	.incbin "sound/direct_sound_samples/sa2/unknown_8ae9bb4.bin"

	.align 2
DirectSoundWaveData_sa2_14::
	.incbin "sound/direct_sound_samples/sa2/unknown_8aea788.bin"

	.align 2
DirectSoundWaveData_sa2_15::
	.incbin "sound/direct_sound_samples/sa2/korg_trinity__30303_mega_bass_1.bin"

	.align 2
DirectSoundWaveData_sa2_16::
	.incbin "sound/direct_sound_samples/sa2/korg_trinity__30303_mega_bass_2.bin"

	.align 2
DirectSoundWaveData_sa2_17::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__pr_d__019_organ_3__5.bin"

	.align 2
DirectSoundWaveData_sa2_18::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__alto_sax.bin"

	.align 2
DirectSoundWaveData_sa2_19::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__timpani.bin"

	.align 2
DirectSoundWaveData_sa2_20::
	.incbin "sound/direct_sound_samples/sa2/roland_sr_jv80_02__186_harp_1.bin"

	.align 2
DirectSoundWaveData_sa2_21::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__pr_d__019_organ_3__6.bin"

	.align 2
DirectSoundWaveData_sa2_22::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__piano_2.bin"

	.align 2
DirectSoundWaveData_sa2_23::
	.incbin "sound/direct_sound_samples/sa2/korg_trinity__music_box_sw1.bin"

	.align 2
DirectSoundWaveData_sa2_24::
	.incbin "sound/direct_sound_samples/sa2/roland_sr_jv80_02__french_horn_sc_x4.bin"

	.align 2
DirectSoundWaveData_sa2_25::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__orchestra_hit.bin"

	.align 2
DirectSoundWaveData_sa2_26::
	.incbin "sound/direct_sound_samples/sa2/roland_sr_jv80_02__vi_sect_mono.bin"

	.align 2
DirectSoundWaveData_sa2_27::
	.incbin "sound/direct_sound_samples/sa2/korg_01_w__16_piano.bin"

	.align 2
DirectSoundWaveData_sa2_28::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B04840.bin"

	.align 2
DirectSoundWaveData_sa2_29::
	.incbin "sound/direct_sound_samples/sa2/korg_01_w__vs_bells_1_1.bin"

	.align 2
DirectSoundWaveData_sa2_30::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B0C95C.bin"

	.align 2
DirectSoundWaveData_sa2_31::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B0F724_sa1_final_boss_choir.bin"

	.align 2
DirectSoundWaveData_sa2_32:: @ 0x8B109B8
	.incbin "sound/direct_sound_samples/sa2/sfx/sa1_intro_wind.bin"

	.align 2
DirectSoundWaveData_sa2_33:: @ 0x8B18DD0
	.incbin "sound/direct_sound_samples/sa2/sfx/sa1_intro_emerald.bin"

	.align 2
DirectSoundWaveData_sa2_34:: @ 0x8B1E9F0
	.incbin "sound/direct_sound_samples/sa2/korg_trinity__dads_jazz_guitar.bin"

	.align 2
DirectSoundWaveData_sa2_35:: @ 0x8B20204
	.incbin "sound/direct_sound_samples/sa2/unknown_8B20204.bin"

	.align 2
DirectSoundWaveData_sa2_36:: @ 0x8B21DC8
	.incbin "sound/direct_sound_samples/sa2/korg_trinity__standard_kit_1.bin"

	.align 2
DirectSoundWaveData_sa2_37:: @ 0x8B22678
	.incbin "sound/direct_sound_samples/sa2/korg_trinity__standard_kit_2.bin"

	.align 2
DirectSoundWaveData_sa2_38:: @ 0x8B232F0
	.incbin "sound/direct_sound_samples/sa2/korg_trinity__standard_kit_3.bin"

	.align 2
DirectSoundWaveData_sa2_39:: @ 0x8B24488
	.incbin "sound/direct_sound_samples/sa2/korg_trinity__standard_kit_4.bin"

	.align 2
DirectSoundWaveData_sa2_40::
	.incbin "sound/direct_sound_samples/sa2/korg_trinity__standard_kit_5.bin"

	.align 2
DirectSoundWaveData_sa2_41::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B257FC__maybe_roland_jv2080_jazz_drum_set1.bin"

	.align 2
DirectSoundWaveData_sa2_42::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__jazz_drum_set1__1.bin"

	.align 2
DirectSoundWaveData_sa2_43::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__jazz_drum_set1__2.bin"

	.align 2
DirectSoundWaveData_sa2_44::
	.incbin "sound/direct_sound_samples/sa2/korg_trinity__mega_mix_kit_1.bin"

	.align 2
DirectSoundWaveData_sa2_45::
	.incbin "sound/direct_sound_samples/sa2/korg_trinity__mega_mix_kit_2.bin"

	.align 2
DirectSoundWaveData_sa2_46::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B2EEB8.bin"

	.align 2
DirectSoundWaveData_sa2_47::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080_power_drum_set.bin"

	.align 2
DirectSoundWaveData_sa2_48::
	.incbin "sound/direct_sound_samples/sa2/sfx/spin_attack.bin"

	.align 2
DirectSoundWaveData_sa2_49::
	.incbin "sound/direct_sound_samples/sa2/sfx/score_count_complete.bin"

	.align 2
DirectSoundWaveData_sa2_50::
	.incbin "sound/direct_sound_samples/sa2/sfx/ring.bin"

	.align 2
DirectSoundWaveData_sa2_51::
	.incbin "sound/direct_sound_samples/sa2/sfx/rings_lost.bin"

	.align 2
DirectSoundWaveData_sa2_52::
	.incbin "sound/direct_sound_samples/sa2/sfx/sa1_goal.bin"

	.align 2
DirectSoundWaveData_sa2_53::
	.incbin "sound/direct_sound_samples/sa2/voices/cheese/wheewopog.bin"

	.align 2
DirectSoundWaveData_sa2_54::
	.incbin "sound/direct_sound_samples/sa2/voices/cheese/baa.bin"

	.align 2
DirectSoundWaveData_sa2_55::
	.incbin "sound/direct_sound_samples/sa2/voices/cheese/ooooh.bin"

	.align 2
DirectSoundWaveData_sa2_56::
	.incbin "sound/direct_sound_samples/sa2/voices/cheese/attack.bin"

	.align 2
DirectSoundWaveData_sa2_57::
	.incbin "sound/direct_sound_samples/sa2/voices/cheese/hmm_huh.bin"

	.align 2
DirectSoundWaveData_sa2_58::
	.incbin "sound/direct_sound_samples/sa2/voices/cheese/huh.bin"

	.align 2
DirectSoundWaveData_sa2_59::
	.incbin "sound/direct_sound_samples/sa2/voices/cheese/hihihi.bin"

	.align 2
DirectSoundWaveData_sa2_60::
	.incbin "sound/direct_sound_samples/sa2/korg_trinity__jazz_brush_kits.bin"

	.align 2
DirectSoundWaveData_sa2_61::
	.incbin "sound/direct_sound_samples/sa2/sfx/8B51EBC.bin"

	.align 2
DirectSoundWaveData_voice__announcer__sonic_advance_2:
	.incbin "sound/direct_sound_samples/sa2/voices/announcer/sonic_advance_2.bin"

	.align 2
DirectSoundWaveData_voice__announcer__sonic:
	.incbin "sound/direct_sound_samples/sa2/voices/announcer/sonic.bin"

	.align 2
DirectSoundWaveData_sa2_62::
	.incbin "sound/direct_sound_samples/sa2/voices/announcer/tails.bin"

	.align 2
DirectSoundWaveData_sa2_63::
	.incbin "sound/direct_sound_samples/sa2/voices/announcer/knuckles.bin"

	.align 2
DirectSoundWaveData_sa2_64::
	.incbin "sound/direct_sound_samples/sa2/voices/announcer/amy.bin"

	.align 2
DirectSoundWaveData_voice__announcer__cream:
	.incbin "sound/direct_sound_samples/sa2/voices/announcer/cream.bin"

	.align 2
DirectSoundWaveData_sa2_65::
	.incbin "sound/direct_sound_samples/sa2/voices/announcer/countdown_3.bin"

	.align 2
DirectSoundWaveData_sa2_66::
	.incbin "sound/direct_sound_samples/sa2/voices/announcer/countdown_2.bin"

	.align 2
DirectSoundWaveData_sa2_67::
	.incbin "sound/direct_sound_samples/sa2/voices/announcer/countdown_1.bin"

	.align 2
DirectSoundWaveData_sa2_68::
	.incbin "sound/direct_sound_samples/sa2/voices/announcer/countdown_go.bin"

	.align 2
DirectSoundWaveData_sa2_69::
	.incbin "sound/direct_sound_samples/sa2/voices/announcer/congratulations.bin"

	.align 2
DirectSoundWaveData_sa2_70:: @ 0x8B6BA40
	.incbin "sound/direct_sound_samples/sa2/sfx/music_plant_spring.bin"

    @ Music Plant - 
	.align 2
DirectSoundWaveData_sa2_71:: @ 0x8B6FA94
	.incbin "sound/direct_sound_samples/sa2/sfx/8B6FA94.bin"

	.align 2
DirectSoundWaveData_sa2_72:: @ 0x8B70C1C
	.incbin "sound/direct_sound_samples/sa2/sfx/music_plant_note.bin"

	.align 2
DirectSoundWaveData_sa2_73:: @ 0x8B72E4C
	.incbin "sound/direct_sound_samples/sa2/sfx/music_plant_note_block.bin"

	.align 2
DirectSoundWaveData_sa2_74::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B756E4.bin"

	.align 2
DirectSoundWaveData_sa2_75::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B78148.bin"

	.align 2
DirectSoundWaveData_sa2_76:: @ 0x8B7A79C
	.incbin "sound/direct_sound_samples/sa2/sfx/music_plant_guitar.bin"

	.align 2
DirectSoundWaveData_sa2_77:: @ 0x8B7E428
	.incbin "sound/direct_sound_samples/sa2/sfx/german_flute.bin"

	.align 2
DirectSoundWaveData_sa2_78::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B80688.bin"

	.align 2
DirectSoundWaveData_sa2_79::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B84450.bin"

	.align 2
DirectSoundWaveData_sa2_80::
	.incbin "sound/direct_sound_samples/sa2/korg_01_w__vs_bells_1_2.bin"

	.align 2
DirectSoundWaveData_sa2_81::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B91D70.bin"

	.align 2
DirectSoundWaveData_sa2_82::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B940F0.bin"

	.align 2
DirectSoundWaveData_sa2_83::
	.incbin "sound/direct_sound_samples/sa2/korg_01_w__expecting.bin"

	.align 2
DirectSoundWaveData_sa2_84::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B9A988.bin"

	.align 2
DirectSoundWaveData_sa2_85::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B9AD68.bin"

	.align 2
DirectSoundWaveData_sa2_86::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B9B1C0.bin"

	.align 2
DirectSoundWaveData_sa2_87::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B9BB3C.bin"

	.align 2
DirectSoundWaveData_sa2_88::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B9BF9C.bin"

	.align 2
DirectSoundWaveData_sa2_89::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B9C408.bin"

	.align 2
DirectSoundWaveData_sa2_90::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B9C894.bin"

	.align 2
DirectSoundWaveData_sa2_91::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B9D1C0.bin"

	.align 2
DirectSoundWaveData_sa2_92::
	.incbin "sound/direct_sound_samples/sa2/unknown_8B9D718.bin"

	.align 2
DirectSoundWaveData_sa2_93::
	.incbin "sound/direct_sound_samples/sa2/korg_01_w__spectrum.bin"

	.align 2
DirectSoundWaveData_sa2_94::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__harmonica.bin"

	.align 2
DirectSoundWaveData_sa2_95::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__pr_d__019_organ_3__7.bin"

	.align 2
DirectSoundWaveData_sa2_96::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__pr_d__019_organ_3__8.bin"

	.align 2
DirectSoundWaveData_sa2_97::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BA62E0.bin"

	.align 2
DirectSoundWaveData_sa2_98::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BA6AA0.bin"

	.align 2
DirectSoundWaveData_sa2_99:: @ 0x8BAA2DC
	.incbin "sound/direct_sound_samples/sa2/e_mu_morpheus__factory_rom_presets__bank_0__PAD__45_mechanik.bin"

	.align 2
DirectSoundWaveData_sa2_100::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BAFDC0.bin"

	.align 2
DirectSoundWaveData_sa2_101::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BB152C.bin"

	.align 2
DirectSoundWaveData_sa2_102::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BB2CAC.bin"

	.align 2
DirectSoundWaveData_sa2_103::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BB4C60.bin"

	.align 2
DirectSoundWaveData_sa2_104::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BB672C.bin"

	.align 2
DirectSoundWaveData_sa2_105::
	.incbin "sound/direct_sound_samples/sa2/unknown_BB8F2C.bin"

	.align 2
DirectSoundWaveData_sa2_106:: @ 0x8BBA360
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__pr_d__019_organ_3__9.bin"

	.align 2
DirectSoundWaveData_sa2_107::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__pan_flute.bin"

	.align 2
DirectSoundWaveData_sa2_108::
	.incbin "sound/direct_sound_samples/sa2/korg_trinity__studio_strato.bin"

	.align 2
DirectSoundWaveData_sa2_109::
	.incbin "sound/direct_sound_samples/sa2/unknown_8bbd0e4.bin"

	.align 2
DirectSoundWaveData_sa2_110::
	.incbin "sound/direct_sound_samples/sa2/roland_sr_jv80_02__oboe_1.bin"

	.align 2
DirectSoundWaveData_sa2_111::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BC311C.bin"

	.align 2
DirectSoundWaveData_sa2_112::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BC3DD4__roland_sr_jv80_02__someTubular.bin"

	.align 2
DirectSoundWaveData_sa2_113:: @ 0x8BC6304
	.incbin "sound/direct_sound_samples/sa2/steinberg_virtual_guitarist__electric_guitar__ultra_ii__punish.bin"

	.align 2
DirectSoundWaveData_sa2_114::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BC7C58.bin"

	.align 2
DirectSoundWaveData_sa2_115::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BCCBD4.bin"

	.align 2
DirectSoundWaveData_sa2_116::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BCD1DC.bin"

	.align 2
DirectSoundWaveData_sa2_117::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BCD85C.bin"

	.align 2
DirectSoundWaveData_sa2_118::
	.incbin "sound/direct_sound_samples/sa2/steinberg_virtual_guitarist__acoustic_guitar__teenie__ringing_1.bin"

	.align 2
DirectSoundWaveData_sa2_119::
	.incbin "sound/direct_sound_samples/sa2/steinberg_virtual_guitarist__acoustic_guitar__teenie__ringing_2.bin"

	.align 2
DirectSoundWaveData_sa2_120::
	.incbin "sound/direct_sound_samples/sa2/steinberg_virtual_guitarist__acoustic_guitar__teenie__ringing_3.bin"

	.align 2
DirectSoundWaveData_sa2_121::
	.incbin "sound/direct_sound_samples/sa2/steinberg_virtual_guitarist__acoustic_guitar__teenie__ringing_4.bin"

	.align 2
DirectSoundWaveData_sa2_122::
	.incbin "sound/direct_sound_samples/sa2/steinberg_virtual_guitarist__acoustic_guitar__teenie__ringing_5.bin"

	.align 2
DirectSoundWaveData_sa2_123::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BD26FC.bin"

	.align 2
DirectSoundWaveData_sa2_124::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BD2F00.bin"

	.align 2
DirectSoundWaveData_sa2_125::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BD3704.bin"

	.align 2
DirectSoundWaveData_sa2_126::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BD4838.bin"

	.align 2
DirectSoundWaveData_sa2_127::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BD554C.bin"

	.align 2
DirectSoundWaveData_sa2_128::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_4_loop_1.bin"

	.align 2
DirectSoundWaveData_sa2_129::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_4_loop_2.bin"

	.align 2
DirectSoundWaveData_sa2_130::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_4_loop_3.bin"

	.align 2
DirectSoundWaveData_sa2_131::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_4_loop_4.bin"

	.align 2
DirectSoundWaveData_sa2_132::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_4_loop_5.bin"

	.align 2
DirectSoundWaveData_sa2_133::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_4_loop_6.bin"

	.align 2
DirectSoundWaveData_sa2_134::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_4_loop_7.bin"

	.align 2
DirectSoundWaveData_sa2_135::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_4_loop_8.bin"

	.align 2
DirectSoundWaveData_sa2_136::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_4_loop_9.bin"

	.align 2
DirectSoundWaveData_sa2_137::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_4_loop_10.bin"

	.align 2
DirectSoundWaveData_sa2_138::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_5_loop_0.bin"

	.align 2
DirectSoundWaveData_sa2_139::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_5_loop_1.bin"

	.align 2
DirectSoundWaveData_sa2_140::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_5_loop_2.bin"

	.align 2
DirectSoundWaveData_sa2_141::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_5_loop_3.bin"

	.align 2
DirectSoundWaveData_sa2_142::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_5_loop_4.bin"

	.align 2
DirectSoundWaveData_sa2_143::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_5_loop_5.bin"

	.align 2
DirectSoundWaveData_sa2_144::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_5_loop_6.bin"

	.align 2
DirectSoundWaveData_sa2_145::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_5_loop_7.bin"

	.align 2
DirectSoundWaveData_sa2_146::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_5_loop_8.bin"

	.align 2
DirectSoundWaveData_sa2_147::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_5_loop_9.bin"

	.align 2
DirectSoundWaveData_sa2_148::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_5_loop_10.bin"

	.align 2
DirectSoundWaveData_sa2_149::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_5_loop_11.bin"

	.align 2
DirectSoundWaveData_sa2_150::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_5_loop_12.bin"

	.align 2
DirectSoundWaveData_sa2_151::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_5_loop_13.bin"

	.align 2
DirectSoundWaveData_sa2_152::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_5_loop_14.bin"

	.align 2
DirectSoundWaveData_sa2_153::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pH_v1__84_5_loop_15.bin"

	.align 2
DirectSoundWaveData_sa2_154::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pG_v5__83_5_loop_1.bin"

	.align 2
DirectSoundWaveData_sa2_155::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pG_v5__83_5_loop_2.bin"

	.align 2
DirectSoundWaveData_sa2_156::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pG_v5__83_5_loop_3.bin"

	.align 2
DirectSoundWaveData_sa2_157::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pG_v5__83_5_loop_4.bin"

	.align 2
DirectSoundWaveData_sa2_158::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pG_v5__83_5_loop_5.bin"

	.align 2
DirectSoundWaveData_sa2_159::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pG_v5__83_5_loop_6.bin"

	.align 2
DirectSoundWaveData_sa2_160::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pG_v5__83_5_loop_7.bin"

	.align 2
DirectSoundWaveData_sa2_161::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pG_v5__83_5_loop_8.bin"

	.align 2
DirectSoundWaveData_sa2_162::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pG_v5__83_5_loop_9.bin"

	.align 2
DirectSoundWaveData_sa2_163::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pG_v5__83_5_loop_10.bin"

	.align 2
DirectSoundWaveData_sa2_164::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pG_v5__83_5_loop_11.bin"

	.align 2
DirectSoundWaveData_sa2_165::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pG_v5__83_5_loop_12.bin"

	.align 2
DirectSoundWaveData_sa2_166::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pG_v5__83_5_loop_13.bin"

	.align 2
DirectSoundWaveData_sa2_167::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pG_v5__83_5_loop_14.bin"

	.align 2
DirectSoundWaveData_sa2_168::
	.incbin "sound/direct_sound_samples/sa2/eastwest_techno__industrial_pG_v5__83_5_loop_15.bin"

	.align 2
DirectSoundWaveData_sa2_169::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BE84CC.bin"

	.align 2
DirectSoundWaveData_sa2_170::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BE8B70.bin"

	.align 2
DirectSoundWaveData_sa2_171::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BE8F8C.bin"

	.align 2
DirectSoundWaveData_sa2_172::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BE96B0.bin"

	.align 2
DirectSoundWaveData_sa2_173::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BE9A64.bin"

	.align 2
DirectSoundWaveData_sa2_174::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BEA558.bin"

	.align 2
DirectSoundWaveData_sa2_175::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BEAC68.bin"

	.align 2
DirectSoundWaveData_sa2_176::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BEB050.bin"

	.align 2
DirectSoundWaveData_sa2_177::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BEB6F8.bin"

	.align 2
DirectSoundWaveData_sa2_178::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BEBB08.bin"

	.align 2
DirectSoundWaveData_sa2_179::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BEC1F4.bin"

	.align 2
DirectSoundWaveData_sa2_180::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BEC5E0.bin"

	.align 2
DirectSoundWaveData_sa2_181::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BECC28.bin"

	.align 2
DirectSoundWaveData_sa2_182::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BED0D0.bin"

	.align 2
DirectSoundWaveData_sa2_183::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BED77C.bin"

	.align 2
DirectSoundWaveData_sa2_184::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BEDBC4.bin"

	.align 2
DirectSoundWaveData_sa2_185::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BEE23C.bin"

	.align 2
DirectSoundWaveData_sa2_186::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BEE66C.bin"

	.align 2
DirectSoundWaveData_sa2_187::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BEECEC.bin"

	.align 2
DirectSoundWaveData_sa2_188::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BEF12C.bin"

	.align 2
DirectSoundWaveData_sa2_189::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BEF76C.bin"

	.align 2
DirectSoundWaveData_sa2_190::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BEFBF8.bin"

	.align 2
DirectSoundWaveData_sa2_191::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF0268.bin"

	.align 2
DirectSoundWaveData_sa2_192::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF0708.bin"

	.align 2
DirectSoundWaveData_sa2_193::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF0DBC.bin"

	.align 2
DirectSoundWaveData_sa2_194::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF11CC.bin"

	.align 2
DirectSoundWaveData_sa2_195::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF1878.bin"

	.align 2
DirectSoundWaveData_sa2_196::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF1CA4.bin"

	.align 2
DirectSoundWaveData_sa2_197::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF27BC.bin"

	.align 2
DirectSoundWaveData_sa2_198::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF2DCC.bin"

	.align 2
DirectSoundWaveData_sa2_199::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF32F8.bin"

	.align 2
DirectSoundWaveData_sa2_200::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF3860.bin"

	.align 2
DirectSoundWaveData_sa2_201::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF3D74.bin"

	.align 2
DirectSoundWaveData_sa2_202::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF42D8.bin"

	.align 2
DirectSoundWaveData_sa2_203::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF4834.bin"

	.align 2
DirectSoundWaveData_sa2_204::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF4D94.bin"

	.align 2
DirectSoundWaveData_sa2_205::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF52B0.bin"

	.align 2
DirectSoundWaveData_sa2_206::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF5814.bin"

	.align 2
DirectSoundWaveData_sa2_207::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF5D34.bin"

	.align 2
DirectSoundWaveData_sa2_208::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF6250.bin"

	.align 2
DirectSoundWaveData_sa2_209::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF6774.bin"

	.align 2
DirectSoundWaveData_sa2_210::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF6C70.bin"

	.align 2
DirectSoundWaveData_sa2_211::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF7244.bin"

	.align 2
DirectSoundWaveData_sa2_212::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF7794.bin"

	.align 2
DirectSoundWaveData_sa2_213::
	.incbin "sound/direct_sound_samples/sa2/unknown_8BF7CBC.bin"

@ Starts synth sample section (samples 214->270)
	.align 2
DirectSoundWaveData_sa2_214::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8BF820C.bin"

	.align 2
DirectSoundWaveData_sa2_215::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8BF92B4.bin"

	.align 2
DirectSoundWaveData_sa2_216::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8BF9DB0.bin"

	.align 2
DirectSoundWaveData_sa2_217::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8BFA5B8.bin"

	.align 2
DirectSoundWaveData_sa2_218::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8BFAE34.bin"

	.align 2
DirectSoundWaveData_sa2_219::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8BFBEEC.bin"

	.align 2
DirectSoundWaveData_sa2_220::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8BFCF88.bin"

	.align 2
DirectSoundWaveData_sa2_221::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8BFDA70.bin"

	.align 2
DirectSoundWaveData_sa2_222::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8BFDF50.bin"

	.align 2
DirectSoundWaveData_sa2_223::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8BFE458.bin"

	.align 2
DirectSoundWaveData_sa2_224::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8BFEA24.bin"

	.align 2
DirectSoundWaveData_sa2_225::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8BFEFA8.bin"

	.align 2
DirectSoundWaveData_sa2_226::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8BFF56C.bin"

	.align 2
DirectSoundWaveData_sa2_227::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8BFFAC0.bin"

	.align 2
DirectSoundWaveData_sa2_228::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C00064.bin"

	.align 2
DirectSoundWaveData_sa2_229::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C005CC.bin"

	.align 2
DirectSoundWaveData_sa2_230::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C00A50.bin"

	.align 2
DirectSoundWaveData_sa2_231::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C01068.bin"

	.align 2
DirectSoundWaveData_sa2_232::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C015CC.bin"

	.align 2
DirectSoundWaveData_sa2_233::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C01B38.bin"

	.align 2
DirectSoundWaveData_sa2_234::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C020E4.bin"

	.align 2
DirectSoundWaveData_sa2_235::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C025EC.bin"

	.align 2
DirectSoundWaveData_sa2_236::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C02AF4.bin"

	.align 2
DirectSoundWaveData_sa2_237::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C03000.bin"

	.align 2
DirectSoundWaveData_sa2_238::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C03134.bin"

	.align 2
DirectSoundWaveData_sa2_239::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C03674.bin"

	.align 2
DirectSoundWaveData_sa2_240::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C03B7C.bin"

	.align 2
DirectSoundWaveData_sa2_241::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C041A4.bin"

	.align 2
DirectSoundWaveData_sa2_242::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C046A8.bin"

	.align 2
DirectSoundWaveData_sa2_243::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C04C44.bin"

	.align 2
DirectSoundWaveData_sa2_244::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C051BC.bin"

	.align 2
DirectSoundWaveData_sa2_245::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C05700.bin"

	.align 2
DirectSoundWaveData_sa2_246::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C05CB4.bin"

	.align 2
DirectSoundWaveData_sa2_247::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C061F8.bin"

	.align 2
DirectSoundWaveData_sa2_248::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C0673C.bin"

	.align 2
DirectSoundWaveData_sa2_249::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C06C6C.bin"

	.align 2
DirectSoundWaveData_sa2_250::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C071FC.bin"

	.align 2
DirectSoundWaveData_sa2_251::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C07770.bin"

	.align 2
DirectSoundWaveData_sa2_252::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C07C9C.bin"

	.align 2
DirectSoundWaveData_sa2_253::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C081C0.bin"

	.align 2
DirectSoundWaveData_sa2_254::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C086CC.bin"

	.align 2
DirectSoundWaveData_sa2_255::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C087B4.bin"

	.align 2
DirectSoundWaveData_sa2_256::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C08CD0.bin"

	.align 2
DirectSoundWaveData_sa2_257::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C09240.bin"

	.align 2
DirectSoundWaveData_sa2_258::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C097F0.bin"

	.align 2
DirectSoundWaveData_sa2_259::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C09DC4.bin"

	.align 2
DirectSoundWaveData_sa2_260::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C0A2B0.bin"

	.align 2
DirectSoundWaveData_sa2_261::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C0A814.bin"

	.align 2
DirectSoundWaveData_sa2_262::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C0ADC0.bin"

	.align 2
DirectSoundWaveData_sa2_263::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C0B310.bin"

	.align 2
DirectSoundWaveData_sa2_264::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C0B874.bin"

	.align 2
DirectSoundWaveData_sa2_265::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C0BE18.bin"

	.align 2
DirectSoundWaveData_sa2_266::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C0C3E4.bin"

	.align 2
DirectSoundWaveData_sa2_267::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C0C89C.bin"

	.align 2
DirectSoundWaveData_sa2_268::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C0CE1C.bin"

	.align 2
DirectSoundWaveData_sa2_269::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C0D368.bin"

	.align 2
DirectSoundWaveData_sa2_270::
	.incbin "sound/direct_sound_samples/sa2/unk_synth_2/synth_8C0D8A0.bin"

	.align 2
DirectSoundWaveData_sa2_271::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C0DE50.bin"

	.align 2
DirectSoundWaveData_sa2_272::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C0E9F8.bin"

	.align 2
DirectSoundWaveData_sa2_273::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C0F12C.bin"

	.align 2
DirectSoundWaveData_sa2_274::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C0F654.bin"

	.align 2
DirectSoundWaveData_sa2_275::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C0FC88.bin"

	.align 2
DirectSoundWaveData_sa2_276::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C10254.bin"

	.align 2
DirectSoundWaveData_sa2_277::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C10934.bin"

	.align 2
DirectSoundWaveData_sa2_278::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C10E74.bin"

	.align 2
DirectSoundWaveData_sa2_279::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C1153C.bin"

	.align 2
DirectSoundWaveData_sa2_280::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C11A60.bin"

	.align 2
DirectSoundWaveData_sa2_281::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C12124.bin"

	.align 2
DirectSoundWaveData_sa2_282::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C12674.bin"

	.align 2
DirectSoundWaveData_sa2_283::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C12D24.bin"

	.align 2
DirectSoundWaveData_sa2_284::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C13254.bin"

	.align 2
DirectSoundWaveData_sa2_285::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C13928.bin"

	.align 2
DirectSoundWaveData_sa2_286::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C13E3C.bin"

	.align 2
DirectSoundWaveData_sa2_287::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C14524.bin"

	.align 2
DirectSoundWaveData_sa2_288::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C14AA0.bin"

	.align 2
DirectSoundWaveData_sa2_289::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C15164.bin"

	.align 2
DirectSoundWaveData_sa2_290::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C15698.bin"

	.align 2
DirectSoundWaveData_sa2_291::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C15C60.bin"

	.align 2
DirectSoundWaveData_sa2_292::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C162A4.bin"

	.align 2
DirectSoundWaveData_sa2_293::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C16970.bin"

	.align 2
DirectSoundWaveData_sa2_294::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C16EB8.bin"

	.align 2
DirectSoundWaveData_sa2_295::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C17584.bin"

	.align 2
DirectSoundWaveData_sa2_296::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C17A94.bin"

	.align 2
DirectSoundWaveData_sa2_297::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C18188.bin"

	.align 2
DirectSoundWaveData_sa2_298::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C186E8.bin"

	.align 2
DirectSoundWaveData_sa2_299::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C18D8C.bin"

	.align 2
DirectSoundWaveData_sa2_300::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C192A8.bin"

	.align 2
DirectSoundWaveData_sa2_301::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C1998C.bin"

	.align 2
DirectSoundWaveData_sa2_302::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C19EB8.bin"

	.align 2
DirectSoundWaveData_sa2_303::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C1A3F4.bin"

	.align 2
DirectSoundWaveData_sa2_304::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C1A900.bin"

	.align 2
DirectSoundWaveData_sa2_305::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C1AE50.bin"

	.align 2
DirectSoundWaveData_sa2_306::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C1B380.bin"

	.align 2
DirectSoundWaveData_sa2_307::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C1B928.bin"

	.align 2
DirectSoundWaveData_sa2_308::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C1BE0C.bin"

	.align 2
DirectSoundWaveData_sa2_309::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C1C378.bin"

	.align 2
DirectSoundWaveData_sa2_310::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C1C884.bin"

	.align 2
DirectSoundWaveData_sa2_311::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C1CDB8.bin"

	.align 2
DirectSoundWaveData_sa2_312::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C1D2E0.bin"

	.align 2
DirectSoundWaveData_sa2_313::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C1D7EC.bin"

	.align 2
DirectSoundWaveData_sa2_314::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C1DD2C.bin"

	.align 2
DirectSoundWaveData_sa2_315::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C1E29C.bin"

	.align 2
DirectSoundWaveData_sa2_316::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C1E760.bin"

	.align 2
DirectSoundWaveData_sa2_317::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C1ED70.bin"

	.align 2
DirectSoundWaveData_sa2_318::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C1F268.bin"

	.align 2
DirectSoundWaveData_sa2_319::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C1FD70.bin"

	.align 2
DirectSoundWaveData_sa2_320::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C202D0.bin"

	.align 2
DirectSoundWaveData_sa2_321::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C207D0.bin"

	.align 2
DirectSoundWaveData_sa2_322::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C212B8.bin"

	.align 2
DirectSoundWaveData_sa2_323::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C218C0.bin"

	.align 2
DirectSoundWaveData_sa2_324::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C21D18.bin"

	.align 2
DirectSoundWaveData_sa2_325::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C22298.bin"

	.align 2
DirectSoundWaveData_sa2_326::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C22760.bin"

	.align 2
DirectSoundWaveData_sa2_327::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C23218.bin"

	.align 2
DirectSoundWaveData_sa2_328::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C23CA8.bin"

	.align 2
DirectSoundWaveData_sa2_329::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C242A8.bin"

	.align 2
DirectSoundWaveData_sa2_330::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C24730.bin"

	.align 2
DirectSoundWaveData_sa2_331::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C24C80.bin"

	.align 2
DirectSoundWaveData_sa2_332::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C2572C.bin"

	.align 2
DirectSoundWaveData_sa2_333::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C25D2C.bin"

	.align 2
DirectSoundWaveData_sa2_334::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C261B4.bin"

	.align 2
DirectSoundWaveData_sa2_335::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C26724.bin"

	.align 2
DirectSoundWaveData_sa2_336::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C26CA0.bin"

	.align 2
DirectSoundWaveData_sa2_337::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C271B8.bin"

	.align 2
DirectSoundWaveData_sa2_338::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C27770.bin"

	.align 2
DirectSoundWaveData_sa2_339::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C27C58.bin"

	.align 2
DirectSoundWaveData_sa2_340::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C281A8.bin"

	.align 2
DirectSoundWaveData_sa2_341::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C28CFC.bin"

	.align 2
DirectSoundWaveData_sa2_342::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C295D0.bin"

	.align 2
DirectSoundWaveData_sa2_343::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C29BF0.bin"

	.align 2
DirectSoundWaveData_sa2_344::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C2A158.bin"

	.align 2
DirectSoundWaveData_sa2_345::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C2AC00.bin"

	.align 2
DirectSoundWaveData_sa2_346::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C2B22C.bin"

	.align 2
DirectSoundWaveData_sa2_347::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C2B6EC.bin"

	.align 2
DirectSoundWaveData_sa2_348::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C2BC58.bin"

	.align 2
DirectSoundWaveData_sa2_349::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C2C0F8.bin"

	.align 2
DirectSoundWaveData_sa2_350::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C2CBC4.bin"

	.align 2
DirectSoundWaveData_sa2_351::
	.incbin "sound/direct_sound_samples/sa2/amen_break/amen_break_8C2D494.bin"

	.align 2
DirectSoundWaveData_sa2_352::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C2DEF4.bin"

	.align 2
DirectSoundWaveData_sa2_353::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C2E44C.bin"

	.align 2
DirectSoundWaveData_sa2_354::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C2E8CC.bin"

	.align 2
DirectSoundWaveData_sa2_355::
	.incbin "sound/direct_sound_samples/sa2/guitar_8C2ED58.bin"

	.align 2
DirectSoundWaveData_sa2_356::
	.incbin "sound/direct_sound_samples/sa2/guitar_8C2F314.bin"

	.align 2
DirectSoundWaveData_sa2_357:: @ 0x8C2F978
	.incbin "sound/direct_sound_samples/sa2/korg_01_w__a81_flute.bin"

	.align 2
DirectSoundWaveData_sa2_358:: @ 0x8C30F08
	.incbin "sound/direct_sound_samples/sa2/korg_01_w__combi__bank_a__a14_whammy_and_pad.bin"

	.align 2
DirectSoundWaveData_sa2_359::
	.incbin "sound/direct_sound_samples/sa2/some_heavy_guitar__8C34DFC.bin"

	.align 2
DirectSoundWaveData_sa2_360::
	.incbin "sound/direct_sound_samples/sa2/some_synth_maybe__8C35C68.bin"

	.align 2
DirectSoundWaveData_sa2_361:: @ 0x8C37240
	.incbin "sound/direct_sound_samples/sa2/roland_u220__p11_heavy_guitar_011.bin"

	.align 2
DirectSoundWaveData_sa2_362::
	.incbin "sound/direct_sound_samples/sa2/some_unk_organ__8C382F4.bin"

	.align 2
DirectSoundWaveData_sa2_363::
	.incbin "sound/direct_sound_samples/sa2/some_unk_organ__8C3A298.bin"

	.align 2
DirectSoundWaveData_sa2_364::
	.incbin "sound/direct_sound_samples/sa2/unk_crash__8C3BC34.bin"

	.align 2
DirectSoundWaveData_sa2_365::
	.incbin "sound/direct_sound_samples/sa2/unknown_synth__8C3D53C.bin"

	.align 2
DirectSoundWaveData_sa2_366::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C3F3E0.bin"

	.align 2
DirectSoundWaveData_sa2_367::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C40314.bin"

	.align 2
DirectSoundWaveData_sa2_368::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C41284.bin"

	.align 2
DirectSoundWaveData_sa2_369:: @ 0x8C41820
	.incbin "sound/direct_sound_samples/sa2/korg_01_w__b_b22_brass1.bin"

	.align 2
DirectSoundWaveData_sa2_370::
	.incbin "sound/direct_sound_samples/sa2/unknown_piano__8C42488.bin"

	.align 2
DirectSoundWaveData_sa2_371::
	.incbin "sound/direct_sound_samples/sa2/unknown_piano__8C46A48.bin"

	.align 2
DirectSoundWaveData_sa2_372::
	.incbin "sound/direct_sound_samples/sa2/unknown_piano__8C4991C.bin"

	.align 2
DirectSoundWaveData_sa2_373::
	.incbin "sound/direct_sound_samples/sa2/korg_01_w__prog__bank_a__a83_flute__b83_englishHm.bin"

	.align 2
DirectSoundWaveData_sa2_374::
	.incbin "sound/direct_sound_samples/sa2/unknown_piano__8C4E120.bin"

	.align 2
DirectSoundWaveData_sa2_375::
	.incbin "sound/direct_sound_samples/sa2/unknown_8C50304.bin"

	.align 2
DirectSoundWaveData_sa2_376::
	.incbin "sound/direct_sound_samples/sa2/unk_harmonica__8C517B0.bin"

	.align 2
DirectSoundWaveData_sa2_377::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__pr_d__019_organ_3__10.bin"

	.align 2
DirectSoundWaveData_sa2_378::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__pr_d__019_organ_3__11.bin"

	.align 2
DirectSoundWaveData_sa2_379::
	.incbin "sound/direct_sound_samples/sa2/roland_jv2080__pr_d__019_organ_3__12.bin"
