	.align 2
voicegroup301:: @ 
	voice_directsound 60, 0, DirectSoundWaveData_mm_dulcimer_low, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_mm_dulcimer_high, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_mm_bassoon_low, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_mm_bassoon_high, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_mm_acoustic_guitar_low, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_mm_acoustic_guitar_high, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_mm_strings_low, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_mm_strings_mid, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_mm_strings_high, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_mm_female_choir_low, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_mm_female_choir_high, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_mm_male_choir_low, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_mm_male_choir_high, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_mm_tambourine_1, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_mm_tambourine_2, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_mm_tambourine_3, 255, 0, 255, 127
