	.align 2
voicegroup402::	@ Sonic Advance 2 - Final Boss
	voice_square_1_alt 60, 0, 0, 2, 0, 3, 1, 3
	voice_square_2_alt 60, 0, 2, 0, 4, 4, 6
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_26, 0, 3, 3, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_stereo_brass_2, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sa2_unknown_8BA6AA0, 255, 250, 18, 250
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 1, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_26, 0, 3, 3, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_vi_sect_mono, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_sa2_019_organ_3__4, 255, 0, 255, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 6, 0, 3
	voice_square_2_alt 60, 0, 2, 1, 6, 0, 4
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_26, 0, 3, 13, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_stereo_brass_2, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sa2_unknown_8B940F0, 255, 250, 18, 250
	voice_square_1_alt 60, 0, 0, 2, 1, 6, 7, 3
	voice_square_2_alt 60, 0, 2, 1, 6, 7, 4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_PAD__45_mechanik, 255, 0, 255, 127
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_26, 0, 3, 3, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 6, 0, 3
	voice_square_2_alt 60, 0, 2, 1, 6, 0, 4
	voice_square_1_alt 60, 0, 0, 2, 1, 6, 7, 3
	voice_square_2_alt 60, 0, 2, 1, 6, 7, 4
	voice_directsound 60, 0, DirectSoundWaveData_sa2_unknown_8BAFDC0, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_186_harp_1, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_unknown_8B80688, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_stereo_brass_2, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sa2_stereo_brass_2, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sa2_019_organ_3__4, 255, 0, 255, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 7, 0
	voice_square_2_alt 60, 0, 2, 0, 0, 7, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_26, 0, 3, 1, 1
	voice_directsound 60, 0, DirectSoundWaveData_sa2_stereo_brass_2, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sa2_186_harp_1, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_vi_sect_mono, 255, 0, 255, 165
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 13, 1
	voice_square_2_alt 60, 0, 1, 0, 0, 13, 1
	voice_directsound 60, 0, DirectSoundWaveData_sa2_unknown_8BAFDC0, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_019_organ_3__4, 255, 0, 255, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 7, 0
	voice_square_2_alt 60, 0, 2, 0, 0, 7, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_26, 0, 3, 1, 3
	voice_directsound 60, 0, DirectSoundWaveData_sa2_vs_bells_1_2, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_vi_sect_mono, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_sa2_unknown_8BA6AA0, 255, 250, 18, 250
	voice_square_1_alt 60, 0, 0, 1, 0, 3, 1, 3
	voice_square_2_alt 60, 0, 1, 0, 4, 4, 6
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_stereo_brass_2, 255, 0, 255, 127
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_26, 0, 3, 1, 3
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 7, 0
	voice_square_2_alt 60, 0, 2, 0, 0, 7, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_019_organ_3__4, 255, 0, 255, 0
voice_directsound 60, 0, DirectSoundWaveData_sa2_spectrum, 255, 0, 128, 235
	voice_directsound 60, 0, DirectSoundWaveData_sa2_bassoon_1, 255, 0, 255, 127
	voice_square_1_alt 60, 0, 0, 2, 0, 3, 1, 3
	voice_square_2_alt 60, 0, 2, 0, 3, 1, 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 2, 1, 6, 7, 3
	voice_square_2_alt 60, 0, 2, 1, 6, 7, 4
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_26, 0, 3, 1, 3
	voice_directsound 60, 0, DirectSoundWaveData_sa2_186_harp_1, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_unknown_8B80688, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_vs_bells_1_2, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_unknown_8BAFDC0, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_stereo_brass_2, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sa2_unknown_8B940F0, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_019_organ_3__4, 255, 0, 255, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 7, 0
	voice_square_2_alt 60, 0, 2, 0, 0, 7, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_26, 0, 3, 1, 1
	voice_directsound 60, 0, DirectSoundWaveData_sa2_stereo_brass_2, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sa2_186_harp_1, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_vi_sect_mono, 255, 0, 255, 165
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 13, 1
	voice_square_2_alt 60, 0, 1, 0, 0, 13, 1
	voice_directsound 60, 0, DirectSoundWaveData_sa2_unknown_8BAFDC0, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_019_organ_3__4, 255, 0, 255, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 7, 0
	voice_square_2_alt 60, 0, 2, 0, 0, 7, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_26, 0, 3, 1, 1
	voice_directsound 60, 0, DirectSoundWaveData_sa2_stereo_brass_2, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sa2_186_harp_1, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_vi_sect_mono, 255, 0, 255, 165
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 13, 1
	voice_square_2_alt 60, 0, 1, 0, 0, 13, 1
	voice_directsound 60, 0, DirectSoundWaveData_sa2_unknown_8BAFDC0, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_sa2_timpani, 255, 0, 255, 127
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 2, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 0, 4
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_26, 0, 2, 9, 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_26, 1, 2, 9, 2
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 2, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 0, 4
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_26, 0, 2, 9, 2
	voice_square_2_alt 60, 0, 2, 0, 4, 0, 4
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 0, 4
	voice_square_2_alt 60, 0, 2, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 0, 4
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_26, 0, 2, 9, 2
	voice_square_2_alt 60, 0, 2, 1, 3, 3, 5
	voice_square_1_alt 60, 0, 0, 2, 1, 3, 3, 5
	voice_square_2_alt 60, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 0, 4
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_26, 0, 2, 9, 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_26, 0, 3, 7, 2
	voice_square_2_alt 60, 0, 2, 0, 6, 0, 2
	voice_square_1_alt 60, 0, 0, 2, 1, 0, 10, 2
	voice_square_2_alt 60, 0, 2, 0, 6, 0, 6
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0
	@voice_keysplit_all voicegroup012
