	.align 2
voicegroup304::	@ 0x08ACEBD4
	voice_directsound 60, 0, DirectSoundWaveData_sa2_21, 255, 0, 255, 0	@08ACEBD4
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_10, 0, 3, 0, 2	@08ACEBE0
	voice_noise 60, 0, 1, 1, 0, 12, 2	@08ACEBEC
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08ACEBF8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08ACEC04
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08ACEC10
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08ACEC1C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08ACEC28
	voice_directsound 60, 0, DirectSoundWaveData_sa2_53, 255, 0, 255, 0	@08ACEC34
	voice_directsound 60, 0, DirectSoundWaveData_sa2_54, 255, 0, 255, 0	@08ACEC40
	voice_directsound 60, 0, DirectSoundWaveData_sa2_55, 255, 0, 255, 0	@08ACEC4C
	voice_directsound 60, 0, DirectSoundWaveData_sa2_56, 255, 0, 255, 0	@08ACEC58
	voice_directsound 60, 0, DirectSoundWaveData_sa2_57, 255, 0, 255, 0	@08ACEC64
	voice_directsound 60, 0, DirectSoundWaveData_sa2_58, 255, 0, 255, 0	@08ACEC70
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_59, 255, 0, 255, 0	@08ACEC7C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08ACEC88
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08ACEC94
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08ACECA0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08ACECAC
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08ACECB8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08ACECC4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08ACECD0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08ACECDC
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08ACECE8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_60, 255, 0, 255, 0	@08ACECF4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_61, 255, 0, 255, 0	@08ACED00
	voice_noise 60, 0, 0, 0, 0, 15, 0	@08ACED0C
	voice_noise 60, 0, 0, 1, 0, 15, 2	@08ACED18
	voice_noise 60, 0, 1, 1, 0, 12, 2	@08ACED24
	voice_square_1_alt 60, 0, 0, 2, 2, 0, 15, 0	@08ACED30
	voice_noise 60, 0, 0, 1, 0, 15, 2	@08ACED3C
	voice_noise 60, 0, 0, 0, 0, 15, 2	@08ACED48
	voice_noise 60, 0, 1, 0, 0, 15, 2	@08ACED54
	voice_square_2_alt 60, 0, 2, 3, 0, 10, 3	@08ACED60
	voice_square_2_alt 60, 0, 1, 0, 2, 0, 0	@08ACED6C
	voice_keysplit_all voicegroup301	@08ACED78
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_32, 255, 0, 255, 0	@08ACED84
