	.align 2
voicegroup316::	@ 0x08AD2108
	voice_keysplit_all voicegroup319	@08AD2108
	voice_keysplit_all voicegroup318	@08AD2114
	voice_keysplit_all voicegroup317	@08AD2120
	voice_keysplit_all voicegroup316	@08AD212C
	voice_keysplit_all voicegroup315	@08AD2138
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_36, 255, 255, 255, 0	@08AD2144
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_37, 255, 0, 255, 0	@08AD2150
	voice_noise 84, 0, 0, 0, 1, 0, 0	@08AD215C
	voice_noise 84, 0, 0, 0, 2, 0, 0	@08AD2168
	voice_noise 84, 0, 0, 0, 3, 7, 0	@08AD2174
	voice_directsound 45, 0, DirectSoundWaveData_sa2_38, 255, 0, 255, 0	@08AD2180
	voice_directsound 50, 0, DirectSoundWaveData_sa2_38, 255, 0, 255, 0	@08AD218C
	voice_directsound 55, 0, DirectSoundWaveData_sa2_38, 255, 0, 255, 0	@08AD2198
	voice_directsound 60, 0, DirectSoundWaveData_sa2_38, 255, 0, 255, 0	@08AD21A4
	voice_directsound 65, 0, DirectSoundWaveData_sa2_38, 255, 0, 255, 0	@08AD21B0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_39, 255, 0, 255, 0	@08AD21BC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_40, 255, 0, 255, 0	@08AD21C8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_41, 255, 0, 255, 0	@08AD21D4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_42, 255, 0, 255, 0	@08AD21E0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_43, 255, 0, 255, 0	@08AD21EC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_44, 255, 0, 255, 0	@08AD21F8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_45, 255, 0, 255, 0	@08AD2204
	voice_directsound 57, 0, DirectSoundWaveData_sa2_42, 255, 0, 255, 0	@08AD2210
	voice_directsound 59, 0, DirectSoundWaveData_sa2_42, 255, 0, 255, 0	@08AD221C
	voice_directsound 61, 0, DirectSoundWaveData_sa2_42, 255, 0, 255, 0	@08AD2228
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD2234
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD2240
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD224C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD2258
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD2264
	voice_directsound 60, 0, DirectSoundWaveData_sa2_123, 255, 0, 255, 0	@08AD2270
	voice_directsound 60, 0, DirectSoundWaveData_sa2_124, 255, 242, 51, 0	@08AD227C
	voice_directsound 70, 0, DirectSoundWaveData_sa2_125, 255, 0, 255, 0	@08AD2288
	voice_directsound 64, 0, DirectSoundWaveData_sa2_126, 255, 0, 255, 0	@08AD2294
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD22A0
	voice_directsound 64, 0, DirectSoundWaveData_sa2_127, 255, 0, 255, 0	@08AD22AC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_128, 255, 0, 255, 0	@08AD22B8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_129, 255, 0, 255, 0	@08AD22C4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_130, 255, 0, 255, 0	@08AD22D0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_131, 255, 0, 255, 0	@08AD22DC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_132, 255, 0, 255, 0	@08AD22E8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD22F4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD2300
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD230C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_133, 255, 0, 255, 0	@08AD2318
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_134, 255, 0, 255, 0	@08AD2324
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_135, 255, 0, 255, 0	@08AD2330
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_136, 255, 0, 255, 0	@08AD233C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_137, 255, 0, 255, 0	@08AD2348
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_138, 255, 0, 255, 0	@08AD2354
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_139, 255, 0, 255, 0	@08AD2360
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_140, 255, 0, 255, 0	@08AD236C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_141, 255, 0, 255, 0	@08AD2378
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_142, 255, 0, 255, 0	@08AD2384
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_143, 255, 0, 255, 0	@08AD2390
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_144, 255, 0, 255, 0	@08AD239C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_145, 255, 0, 255, 0	@08AD23A8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_146, 255, 0, 255, 0	@08AD23B4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_147, 255, 0, 255, 0	@08AD23C0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_148, 255, 0, 255, 0	@08AD23CC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_149, 255, 0, 255, 0	@08AD23D8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_150, 255, 0, 255, 0	@08AD23E4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_151, 255, 0, 255, 0	@08AD23F0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_152, 255, 0, 255, 0	@08AD23FC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_153, 255, 0, 255, 0	@08AD2408
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD2414
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD2420
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD242C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_154, 255, 0, 255, 0	@08AD2438
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_155, 255, 0, 255, 0	@08AD2444
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_156, 255, 0, 255, 0	@08AD2450
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_157, 255, 0, 255, 0	@08AD245C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_158, 255, 0, 255, 0	@08AD2468
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_159, 255, 0, 255, 0	@08AD2474
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_160, 255, 0, 255, 0	@08AD2480
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_161, 255, 0, 255, 0	@08AD248C
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_162, 255, 0, 255, 0	@08AD2498
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_163, 255, 0, 255, 0	@08AD24A4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_164, 255, 0, 255, 0	@08AD24B0
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_165, 255, 0, 255, 0	@08AD24BC
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_166, 255, 0, 255, 0	@08AD24C8
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_167, 255, 0, 255, 0	@08AD24D4
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sa2_168, 255, 0, 255, 0	@08AD24E0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD24EC
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD24F8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD2504
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD2510
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD251C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD2528
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD2534
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD2540
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@08AD254C
