    .align 2
voicegroup300:: @Stone Tower Temple  
    voice_keysplit voicegroup401, KeySplitTable100 @Dulcimer
    voice_directsound 60, 0, DirectSoundWaveData_mm_ocarina, 255, 0, 255, 127
    voice_keysplit voicegroup401, KeySplitTable101 @Bassoon ALT
    voice_directsound 60, 0, DirectSoundWaveData_mm_oboe, 255, 0, 255, 127
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @todo "fiddle"?
    voice_directsound 60, 0, DirectSoundWaveData_mm_harmonica, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_mm_piccolo, 255, 0, 255, 127
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_keysplit voicegroup401, KeySplitTable102 @Acoustic Guitar
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_keysplit voicegroup401, KeySplitTable103 @Strings 1
    voice_keysplit voicegroup401, KeySplitTable103 @Strings 2
    voice_keysplit voicegroup401, KeySplitTable104 @Female Choir
    voice_keysplit voicegroup401, KeySplitTable105 @Male Choir
    voice_directsound 60, 0, DirectSoundWaveData_mm_elves, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_mm_wind, 255, 0, 255, 127
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @empty space
    voice_keysplit voicegroup401, KeySplitTable106 @Tamborine (Percussive)
